### PR TITLE
docs: use stable Rust toolchain for installation

### PR DESCRIPTION
**Pull request by martinvonz**
We don't need the nightly toolchain anymore since #70 (thanks,
@arxanas!).

- [x] Tests pass
- [x] Appropriate changes to README are included in PR

### CODE REVIEW

**Comment by martinvonz** [comment]
@arxanas, LGTY?

**Comment by arxanas** [comment]
LGTM, but it also sounded like we might need nightly for certain M1 builds, so it might be good to put in a troubleshooting section somewhere.

**Review by arxanas — APPROVED** [review]

**Comment by martinvonz** [comment]
> LGTM, but it also sounded like we might need nightly for certain M1 builds, so it might be good to put in a troubleshooting section somewhere.

I only remember seeing https://github.com/martinvonz/jj/issues/74#issuecomment-1048281384, which says that the problem did *not* work on M1 with nightly.

**Comment by arxanas** [comment]
Oh right haha

**Pull request merged**
