### PR TITLE
cli: commit working copy before recovering from stale state

### PR DESCRIPTION
**Pull request by yuja**
If the working copy is dirty and stale, new commit will be created on top
of the stale parent, and the working copy will point to the created commit,
not to the commit which the repo view previously pointed.

I'm not pretty sure if this is @martinvonz suggested, so please let me know
if it's wrong.

# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)

### CODE REVIEW

**Review by martinvonz — COMMENTED** [review]
Thanks for fixing this!

> If the working copy is dirty and stale, new commit will be created on top
> of the stale parent, and the working copy will point to the created commit,
> not to the commit which the repo view previously pointed.
> 
> I'm not pretty sure if this is @martinvonz suggested, so please let me know
> if it's wrong.

Yes, committing the working copy on top of the stale is what I suggested, but I had not actually considered which commit the working copy should point to afterwards.

We may want to add a message explaining what happened and how to recover. Something like:

```
The working copy is stale (not updated since operation abc123), but there were uncommitted changes that prevented an update to operation abc456. You may want to rebase these onto <working-copy commit from abc456> and squash them in.
```

Or if we change it so we update to the commit the repo view previously pointed to:
```
The working copy is stale (not updated since operation abc123), now updating to
operation abc456.
There we uncommitted changes in the working copy that were committed as def123. You may want to rebase these onto @ and squash them in.
```

Hmm, having written that makes it clear that the suggestion of rebasing and squashing is not great because it's likely to cause unnecessary conflicts. It's really the difference compared to the predecessor that should be squashed in. The answer might just be that the real suggestion should be to run some command we don't have yet for resolving divergence. Or we could commit the changes on top of the old working copy instead of amending it. What do you think?

**Comment by yuja** [comment]
> We may want to add a message explaining what happened and how to recover.

Agreed.

> Hmm, having written that makes it clear that the suggestion of rebasing and squashing is not great because it's likely to cause unnecessary conflicts. It's really the difference compared to the predecessor that should be squashed in. The answer might just be that the real suggestion should be to run some command we don't have yet for resolving divergence. Or we could commit the changes on top of the old working copy instead of amending it. What do you think?

If I understand it, rebasing `@` of the stale workspace is valid, but we'll need some extra steps to clean up the divergence.

```
A - B - C (main workspace)
      \ 
        D (secondary workspace)
```

After squashing C into B in main:
```
         D' (rebased secondary)
       /
A - B' - E (main)
  \
    B  - D (stale secondary, invisible)
```

After running jj in stale&dirty secondary:
```
         D' (prev secondary)
       /
A - B' - E (main)
  \
    B  - D'' (current secondary, was stale but revived & committed dirty)
```

`jj rebase -r D'' -d B'` will create a rebased commit `D'''`, and user will need to manually abandon `B` and `D'`. Maybe it's tedious to do so, and printing the full recovery instruction would be too verbose.

**Comment by martinvonz** [comment]
> > We may want to add a message explaining what happened and how to recover.
> 
> Agreed.
> 
> > Hmm, having written that makes it clear that the suggestion of rebasing and squashing is not great because it's likely to cause unnecessary conflicts. It's really the difference compared to the predecessor that should be squashed in. The answer might just be that the real suggestion should be to run some command we don't have yet for resolving divergence. Or we could commit the changes on top of the old working copy instead of amending it. What do you think?
> 
> If I understand it, rebasing `@` of the stale workspace is valid, but we'll need some extra steps to clean up the divergence.
> 
> ```
> A - B - C (main workspace)
>       \ 
>         D (secondary workspace)
> ```
> 
> After squashing C into B in main:
> 
> ```
>          D' (rebased secondary)
>        /
> A - B' - E (main)
>   \
>     B  - D (stale secondary, invisible)
> ```
> 
> After running jj in stale&dirty secondary:
> 
> ```
>          D' (prev secondary)
>        /
> A - B' - E (main)
>   \
>     B  - D'' (current secondary, was stale but revived & committed dirty)
> ```
> 
> `jj rebase -r D'' -d B'` will create a rebased commit `D'''`, and user will need to manually abandon `B` and `D'`. Maybe it's tedious to do so, and printing the full recovery instruction would be too verbose.

Thanks for writing down that example. It really helps make it clear what we're talking about. And yes, full recovery instructions may be too long. We can leave that until we have a command for resolving divergence.

I just realized that we should probably not just look up the working-copy from the `ancestor_op`, we should also start the transaction at that operation because it's logically concurrent with the operation(s) performed in the main repo. That might even make D'' get automatically rebased onto B' when the operations are merged (call `tx.merge_operation()` to do that).

By the way, we may also want to reconsider the automatic updating of stale working copies. I think it can be especially annoying if the user has a build or tests running in that working copy. It may be better to just print a message informing the user that their working copy is supposed to point to some other commit (and include instructions for how to address it). Changing that is of course out of scope of this PR. I'm still curious to hear what you think about it.

**Comment by yuja** [comment]
> I just realized that we should probably not just look up the working-copy from the `ancestor_op`, we should also start the transaction at that operation because it's logically concurrent with the operation(s) performed in the main repo. That might even make D'' get automatically rebased onto B' when the operations are merged (call `tx.merge_operation()` to do that).

I didn't know operation history can also be forked and merged. Yeah, it's more
correct to start the commit op from the `ancestor_op`.

> By the way, we may also want to reconsider the automatic updating of stale working copies. I think it can be especially annoying if the user has a build or tests running in that working copy. It may be better to just print a message informing the user that their working copy is supposed to point to some other commit (and include instructions for how to address it).

Yes. I wouldn't expect `jj st` could bring the checkout to different state.
Snapshotting might also be undesired if the stale working copy was the result
of interrupted checkout.

I think it's even better to not turn the other workspace's checkouts stale.
If a commit is checked out in another workspace, rewriting the ancestor would
inherently create a divergence.

```
         D' (rebased secondary) <-- maybe better to not automatically rebase "D"?
       /
A - B' - E (main)
  \
    B  - D (actual secondary) <-- diverged "B" since "D" is checked out
```

**Comment by martinvonz** [comment]
> I didn't know operation history can also be forked and merged.

You can read more [here](https://github.com/martinvonz/jj/blob/main/docs/technical/concurrency.md).

> I think it's even better to not turn the other workspace's checkouts stale. If a commit is checked out in another workspace, rewriting the ancestor would inherently create a divergence.
> 
> ```
>          D' (rebased secondary) <-- maybe better to not automatically rebase "D"?
>        /
> A - B' - E (main)
>   \
>     B  - D (actual secondary) <-- diverged "B" since "D" is checked out
> ```

I'd prefer to avoid the divergent B if we can. Alternatively, it seems acceptable if we can make it easy for the user to recover from it. There's some context in #13 about different approaches.

**Comment by yuja** [comment]
> I'd prefer to avoid the divergent B if we can. Alternatively, it seems acceptable if we can make it easy for the user to recover from it. There's some context in #13 about different approaches.

Thanks for the pointers. What I don't like about stale checkout is
it's unclear how to examine the situation. If `commit_working_copy()` does
never auto resolve the stale wc (and prints recovery instructions), I can
just use `jj log --at-op <wc-op>` etc. to understand how the checkout
looked before. So I found (2)stale vs (3)divergent in #13 wouldn't matter
for me.

Regarding the recovery, we'll probably need two options. I don't think it's
intuitive to apply that automatically.

* rebase+checkout would roughly do
  1. `commit_working_copy()` `--at-op <wc-op>`
  2. resolve concurrent ops
  3. check out the successor of (1), which should be created by (2)

* clean checkout
  1. `jj checkout` without `commit_working_copy()`

**Comment by martinvonz** [comment]
(Sorry about the delay. I've been busy preparing for my Git Merge talk, and then I had a cold on top of that.)

> > I'd prefer to avoid the divergent B if we can. Alternatively, it seems acceptable if we can make it easy for the user to recover from it. There's some context in #13 about different approaches.
> 
> Thanks for the pointers. What I don't like about stale checkout is it's unclear how to examine the situation. If `commit_working_copy()` does never auto resolve the stale wc (and prints recovery instructions), I can just use `jj log --at-op <wc-op>` etc. to understand how the checkout looked before. So I found (2)stale vs (3)divergent in #13 wouldn't matter for me.

The problem with (3) isn't that the working copy is divergent, it's that there can be any number of ancestors that are also divergent (remember that we don't have anything like Mercurial's evolution to say that one side is obsolete), and it's not obvious for the user to resolve it (or even to tell them how to resolve it). I think I'd therefore prefer (2) but instead of automatically updating, we make every command remind the user that their working copy is stale. How does that sound to you? Would you still prefer (3) even if we didn't auto-update the working copy?

I don't remember why I made it do the update automatically. I know I thought it seemed simpler for some reason. I suspect the reason was that if we instead leave the user with a stale working, we would need to figure out what to do if the user does not immediately update to the working-copy commit from the new operation. If they don't make any changes to the (stale) working-copy commit, it would then remain hidden (assuming we stick to (2)), but as soon as they modify files in the working copy or run `jj describe` or `jj new` etc., the new commit would become visible and would cause any rewritten ancestors to be visible and thus divergent. We could decide that all commands error out when the working copy is stale and the user has to run some special `jj workspace update-stale` or something. What do you think?

> 
> Regarding the recovery, we'll probably need two options. I don't think it's intuitive to apply that automatically.
> 
> * rebase+checkout would roughly do
>   
>   1. `commit_working_copy()` `--at-op <wc-op>`
>   2. resolve concurrent ops
>   3. check out the successor of (1), which should be created by (2)
> * clean checkout
>   
>   1. `jj checkout` without `commit_working_copy()`

Assuming we go with (2) but without auto-update, perhaps it would be most intuitive for the `jj workspace update-stale` command to rebase only the uncommitted changes on top of the checkout from the new operation (maybe setting the description to something like "recovered changes from stale working copy in workspace foo"). Of course, if there were no unsaved changes to recover in the stale working copy, we'd just update the working copy to the desired location without creating a commit on top for recovered changes.

**Comment by yuja** [comment]
> > > I'd prefer to avoid the divergent B if we can. Alternatively, it seems acceptable if we can make it easy for the user to recover from it. There's some context in #13 about different approaches.  
> > 
> > Thanks for the pointers. What I don't like about stale checkout is it's unclear how to examine the situation. If `commit_working_copy()` does never auto resolve the stale wc (and prints recovery instructions), I can just use `jj log --at-op <wc-op>` etc. to understand how the checkout looked before. So I found (2)stale vs (3)divergent in #13 wouldn't matter for me.  
> 
> The problem with (3) isn't that the working copy is divergent, it's that there can be any number of ancestors that are also divergent (remember that we don't have anything like Mercurial's evolution to say that one side is obsolete), and it's not obvious for the user to resolve it (or even to tell them how to resolve it). I think I'd therefore prefer (2) but instead of automatically updating, we make every command remind the user that their working copy is stale. How does that sound to you? Would you still prefer (3) even if we didn't auto-update the working copy?

I can live with (2) or (3) if auto-update is turned off. I understand (2)
is healthier regarding the repository state.

What I like about (3) is that I would notice the problem immediately after
I've rewritten shared ancestor commit. If that's a mistake, I can easily undo
that. The commit graph reflects the exact state (though it's not 100% correct
because, as you mentioned, divergence is actually caused by obsolete commits
pinned by working copy), which would also help understand the situation.

> I don't remember why I made it do the update automatically. I know I thought it seemed simpler for some reason. I suspect the reason was that if we instead leave the user with a stale working, we would need to figure out what to do if the user does not immediately update to the working-copy commit from the new operation. If they don't make any changes to the (stale) working-copy commit, it would then remain hidden (assuming we stick to (2)), but as soon as they modify files in the working copy or run `jj describe` or `jj new` etc., the new commit would become visible and would cause any rewritten ancestors to be visible and thus divergent. We could decide that all commands error out when the working copy is stale and the user has to run some special `jj workspace update-stale` or something. What do you think?

Yeah, I prefer error out over auto-update. Maybe we can also warn when
a commit checked out by another workspace is rebased, so the user can
take action while he remembers what he did.

> > Regarding the recovery, we'll probably need two options. I don't think it's intuitive to apply that automatically.
> > 
> > * rebase+checkout would roughly do
> >   
> >   1. `commit_working_copy()` `--at-op <wc-op>`
> >   2. resolve concurrent ops
> >   3. check out the successor of (1), which should be created by (2)
> > * clean checkout
> >   
> >   1. `jj checkout` without `commit_working_copy()`  
> 
> Assuming we go with (2) but without auto-update, perhaps it would be most intuitive for the `jj workspace update-stale` command to rebase only the uncommitted changes on top of the checkout from the new operation (maybe setting the description to something like "recovered changes from stale working copy in workspace foo"). Of course, if there were no unsaved changes to recover in the stale working copy, we'd just update the working copy to the desired location without creating a commit on top for recovered changes.

I'm not sure if creating a recovery commit is preferred (since it's supposed
to be folded into `@`), but we'll also need a command to discard the working
copy changes to recover from interrupted checkout.

**Comment by martinvonz** [comment]
> > > > I'd prefer to avoid the divergent B if we can. Alternatively, it seems acceptable if we can make it easy for the user to recover from it. There's some context in #13 about different approaches.
> > > 
> > > 
> > > Thanks for the pointers. What I don't like about stale checkout is it's unclear how to examine the situation. If `commit_working_copy()` does never auto resolve the stale wc (and prints recovery instructions), I can just use `jj log --at-op <wc-op>` etc. to understand how the checkout looked before. So I found (2)stale vs (3)divergent in #13 wouldn't matter for me.
> > 
> > 
> > The problem with (3) isn't that the working copy is divergent, it's that there can be any number of ancestors that are also divergent (remember that we don't have anything like Mercurial's evolution to say that one side is obsolete), and it's not obvious for the user to resolve it (or even to tell them how to resolve it). I think I'd therefore prefer (2) but instead of automatically updating, we make every command remind the user that their working copy is stale. How does that sound to you? Would you still prefer (3) even if we didn't auto-update the working copy?
> 
> I can live with (2) or (3) if auto-update is turned off. I understand (2) is healthier regarding the repository state.
> 
> What I like about (3) is that I would notice the problem immediately after I've rewritten shared ancestor commit. If that's a mistake, I can easily undo that. The commit graph reflects the exact state (though it's not 100% correct because, as you mentioned, divergence is actually caused by obsolete commits pinned by working copy), which would also help understand the situation.

Another problem with (3) that I forgot about before is that if some workspace is not currently available, you're kind of stuck with the divergence until you update that workspace. That can happen if the workspace is on a USB drive. It can also  happen if the operation is running on a server and updating a repo that's stored in the cloud, while the working copy is on some machine's local disk. For context, we're planning to have all repos in the cloud at Google but workspaces can be either on a VFS in the cloud or on local disk. We could update workspaces that live in the cloud (but again, we may not want to do that), but we won't be able to update workspaces on local disk.

> > I don't remember why I made it do the update automatically. I know I thought it seemed simpler for some reason. I suspect the reason was that if we instead leave the user with a stale working, we would need to figure out what to do if the user does not immediately update to the working-copy commit from the new operation. If they don't make any changes to the (stale) working-copy commit, it would then remain hidden (assuming we stick to (2)), but as soon as they modify files in the working copy or run `jj describe` or `jj new` etc., the new commit would become visible and would cause any rewritten ancestors to be visible and thus divergent. We could decide that all commands error out when the working copy is stale and the user has to run some special `jj workspace update-stale` or something. What do you think?
> 
> Yeah, I prefer error out over auto-update. Maybe we can also warn when a commit checked out by another workspace is rebased, so the user can take action while he remembers what he did.
> 
> > > Regarding the recovery, we'll probably need two options. I don't think it's intuitive to apply that automatically.
> > > 
> > > * rebase+checkout would roughly do
> > >   
> > >   1. `commit_working_copy()` `--at-op <wc-op>`
> > >   2. resolve concurrent ops
> > >   3. check out the successor of (1), which should be created by (2)
> > > * clean checkout
> > >   
> > >   1. `jj checkout` without `commit_working_copy()`
> > 
> > 
> > Assuming we go with (2) but without auto-update, perhaps it would be most intuitive for the `jj workspace update-stale` command to rebase only the uncommitted changes on top of the checkout from the new operation (maybe setting the description to something like "recovered changes from stale working copy in workspace foo"). Of course, if there were no unsaved changes to recover in the stale working copy, we'd just update the working copy to the desired location without creating a commit on top for recovered changes.
> 
> I'm not sure if creating a recovery commit is preferred (since it's supposed to be folded into `@`)

Yes, you're right. I think we should just amend the current working-copy commit from the old operation and then use the usual 3-way merge of operations to handle it.

> but we'll also need a command to discard the working copy changes to recover from interrupted checkout.

Agreed.

Sorry that I didn't have a clearer picture of all this before. What do you want to do with this PR? Merge it in its current state?

**Comment by yuja** [comment]
> Another problem with (3) that I forgot about before is that if some workspace is not currently available, you're kind of stuck with the divergence until you update that workspace. That can happen if the workspace is on a USB drive. It can also  happen if the operation is running on a server and updating a repo that's stored in the cloud, while the working copy is on some machine's local disk. For context, we're planning to have all repos in the cloud at Google but workspaces can be either on a VFS in the cloud or on local disk. We could update workspaces that live in the cloud (but again, we may not want to do that), but we won't be able to update workspaces on local disk.

Gotcha. We have to deal with a stale working copy in that scenario.

> What do you want to do with this PR? Merge it in its current state?

Nope. I think both you and I don't like the behavior this patch introduces,
and the code wouldn't be reusable to implement the manual recovery command,
so it's better to discard.

**Pull request closed without merging**
