### PR TITLE
docs: mention Sapling as a similar tool

### PR DESCRIPTION
**Pull request by martinvonz**
# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (src/config-schema.json)
- [ ] I have added tests to cover my changes

### CODE REVIEW

**Review by quark-zju — APPROVED** [review]
lgtm!

**Review by PhilipMetzger — APPROVED** [review]
Looks good, the comparison is still missing though :-).

**Comment by martinvonz** [comment]
> Looks good, the comparison is still missing though :-).

Yeah, I know. Feel free to start that doc :)

**Comment by zzl0** [comment]
Thanks for mentioning Sapling in the doc

**Pull request merged**
