### PR TITLE
Add ssh signing backend implementation

### PR DESCRIPTION
**Pull request by julienvincent**
Draft implementation of an ssh signing backend.

This is a continuation to #2728

This has been merged with main. I avoided doing a rebase to try make it easier to colaborate on top of necauqua/signing

# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (cli/src/config-schema.json)
- [ ] I have added tests to cover my changes

### CODE REVIEW

**Comment by martinvonz** [comment]
This PR looks absolutely huge. Maybe you just need to rebase it on top of the main branch?

**Comment by julienvincent** [comment]
@martinvonz It only looked huge because I was targeting necauqua/signing as the PR base.

I'm not really sure how best to contribute this as I'm not the original author of the base PR

**Comment by martinvonz** [comment]
> I changed the base of this PR to main, but I don't know if that's appropriate.

I think that's fine. The initial commits are still recorded as authored by @necauqua, and they gave us their blessing to finish the work.

>I'm not really sure how best to contribute this as I'm not the original author of the base PR.

Your commits depend on the commits in @necauqua's PR, right? If that's the case, we need those commits cleaned up first. I think they would ideally be merged before the additional ssh signing backend on top. What do you think? Can you find time to do that?

**Comment by necauqua** [comment]
Feel free to take over the whole thing, yup, rebase it, do whatever :)

As I've said over there, I've lost steam a bit after making a version that works just for myself (yeeeah, that keeps happening to me), and also I'm busy with a bunch of other stuff, but I'm happy for my changes to not get lost

**Comment by julienvincent** [comment]
> Your commits depend on the commits in @necauqua's PR, right? If that's the case, we need those commits cleaned up first. I think they would ideally be merged before the additional ssh signing backend on top. What do you think? Can you find time to do that?

Yes absolutely I agree - that PR/work would need to land before this one can.

I am certainly willing to take over the work in #2728 but that comes with the caveat that I have very little real rust experience and I'm not sure I have enough free time to deliver on it. I am happy to run with it and see how far I can get!

The maintainers on this project seem very active so I am sure that will help a lot.

---

Thanks for your blessing @necauqua I will open a new rebased PR off of #2728 and try resolve the remaining items.

**Comment by julienvincent** [comment]
Closing in favour of #3007

**Pull request closed without merging**
