### PR TITLE
Trie implementation of the index for unique prefixes

### PR DESCRIPTION
**Pull request by ilyagr**
This is a draft, but might be enough for a discussion.

The CI is failing because I need to fix the benchmark.

This includes https://github.com/martinvonz/jj/pull/994. (I cannot make the diff be relative to it since that branch is in my fork).

# Checklist

If applicable:
- (not planned) I have updated `CHANGELOG.md`
- (not planned) I have updated the documentation (README.md, docs/, demos/)
- [x] I have added tests to cover my changes

### CODE REVIEW

**Comment by martinvonz** [comment]
How does this perform compared to the BTree-based solution? Is it worth the extra complexity?

**Comment by ilyagr** [comment]
Last I checked, it was about 5 times faster at computing each unique prefix and took about the same amount of time to build the index. I was going to check if this is a noticeable speedup on a large repository; I think it might be.

**Comment by yuja** [comment]
FYI, I made experiment that splits commit/change id indices and replace the commit id part with the existing `ReadonlyIndex`. For my "jj" work repo, it appears to save ~4ms of 5ms that needed to populate `commit_change_id_index`.

Suppose there are way more invisible commits, it's probably better to not scan the whole commits at boot time.

**Comment by ilyagr** [comment]
I'm actually a bit sick at the moment, but here are some disorganized thoughts @yuja 

I don't feel strongly one way or the other specifically about storing the commits inside the IdIndex (instead of the Index) or using the existing index functionality. I'm pretty sure @martinvonz prefers the latter, as do you. I think it would be useful to settle on a plan of which we will do in the near future.

I am curious whether the Index is faster or slower than the BTree at computing each prefix. I'm not sure if it matters in practice. I can commit my benchmark, but so far, I haven't been able to match what it shows to what I experience on large repos.

If you have a large hard drive, you can try out your patch on the torvalds/linux repo. I suspect you'll win more than 5ms there, I'm a bit curious how much it will be.

I would like the IdIndex (or some one entity) to contain all the functionality relating to deciding which prefix corresponds to which object. For example, I was hoping to move the following logic into the IdIndex.

https://github.com/martinvonz/jj/blob/24ccd80a5c0b3c4ad7306b7db35adf28a2747a91/lib/src/revset.rs#L193-L203

So, even if the IdIndex calls into the regular index, I'd have everything go through it (or through Repo). This may or may not involve the IdIndex moving to `revsert.rs`. I find it easier (less work, at the very least) to just keep it at the Repo level, but I'm not philosophically opposed to moving. OTOH, you seem to be very efficient at this kind of refactoring :).

Finally, the one feature I wanted to add that would be trivial if we kept everything inside the IdIndex and less so if we split the index would be to list the matching commits when a prefix is ambiguous (matches more than one commit). It should be possible to teach the Index to do that as well, but I haven't figured out how to do it. OTOH, this is merely a "nice to have" feature.

**Comment by yuja** [comment]
> how the regular `Index` works and how optimized it is for prefix-searching.

It's basically a sorted vec of commit ids afaik, so we can do binary search in place of binary tree lookup. I didn't run serious benchmark, but it seems that shortest prefix searching in index is on par with `IdIndex`, and we can reduce the initial cost.

https://github.com/martinvonz/jj/blob/9846bf6c7f28c916e4619bb0b31c50bb284171e1/lib/src/index.rs#L240

> So, even if the IdIndex calls into the regular index, I'd have everything go through it (maybe via Repo). This may or may not involve the IdIndex moving to `revsert.rs`.

I'm not going to change the API of repo layer (except for turning hex id bytes to raw id bytes.) IdIndex/ReadonlyIndex operations can be routed there. Maybe in-memory tree for shallow lookup space (for recent/wip revsets) can be built there.

Anyway, I need to clean up my changes to submit a readable PR. Let's see how that goes.

**Comment by yuja** [comment]
Some numbers from my experiment.

Command to benchmark (measuring initialization cost of `IdIndex`):
```shell
$ cd linux
$ hyperfine --warmup 3 "jj log -r master -T 'commit_id.short_prefix_and_brackets()' --no-commit-working-copy --no-graph"
```
(note: my linux repo contains changes from both "torvalds" and "stable")

Baseline (1bcdcea3ef):
```
  Time (mean ± σ):      4.300 s ±  0.022 s    [User: 4.145 s, System: 0.155 s]
  Range (min … max):    4.261 s …  4.329 s    10 runs
```

Store bytes, not hex in `IdIndex`:
```
  Time (mean ± σ):      3.608 s ±  0.027 s    [User: 3.463 s, System: 0.144 s]
  Range (min … max):    3.568 s …  3.652 s    10 runs
```

`IdIndex` (change_id) + `ReadonlyIndex` (commit_id):
```
  Time (mean ± σ):      1.882 s ±  0.023 s    [User: 1.795 s, System: 0.087 s]
  Range (min … max):    1.849 s …  1.924 s    10 runs
```

Hacked `IdIndex`(`Vec::sort_unstable(), dedup() in place of BTreeMap`) + `ReadonlyIndex`:
```
  Time (mean ± σ):     871.9 ms ±   3.9 ms    [User: 819.2 ms, System: 52.6 ms]
  Range (min … max):   865.0 ms … 877.5 ms    10 runs
```

I'm a bit surprised that `sort_unstable()` is super fast. :)

**Comment by ilyagr** [comment]
> I'm a bit surprised that sort_unstable() is super fast. :)

I'm guessing it might be slower per id shown. If I understood your invocation correctly, it was only showing one id.

I'm also curious about the performance of IdIndex (change_id) + ReadonlyIndex (commit_id) per id shown.

In both cases, the startup time is more important, but we don't want to get anywhere close to the speed of 19d341d32ac5dc07b7b75c1bad15b11b98cfa2ba per id either.

**Comment by yuja** [comment]
> I'm guessing it might be slower per id shown.

Possibly, but I believe it's not significantly slower because the algorithmic complexity is identical. (Prefix tree will be way faster ignoring the initialization cost, though.)

Anyway, the startup time matters in practice since we're likely to show log of recent commits. That's why I measured without `-r'all()'`.

**Comment by ilyagr** [comment]
> Possibly, but I believe it's not significantly slower because the algorithmic complexity is identical.

I think I figured out what my worry was. I wonder if you know the answer off the top of your head . Otherwise, I ought to go and look it up myself.

How does the Index sort the commit ids? If it's supposed to be tolerant of distributed file systems, does that mean that it simply asks the filesystem to do the sorting? My fear is that if the ids aren't sorted correctly on the hard drive, the filesystem will have to do the sorting on every invocation, making the algorithmic complexity worse. OTOH, I expect that this concern was somehow avoided already in the design of the index.

**Comment by yuja** [comment]
> How does the Index sort the commit ids?

Commit ids are saved to index file in sorted form. File name is calculated from the content hash, I suppose. Multiple index files may be stacked (see `jj debug index`), and the top-level one may be in-memory `MutableIndex` which uses `BTree` in place of sorted `Vec`.

**Comment by ilyagr** [comment]
Makes sense, thanks!

So, in principle, we could maybe experiment with `fst` or Sapling's segmented index and give them hash-based file names, potentially not losing the distributed file system support.

**Comment by martinvonz** [comment]
> So, in principle, we could maybe experiment with `fst` or Sapling's segmented index and give them hash-based file names, potentially not losing the distributed file system support.

Yes, I think it may be possible to use segmented changelog with the same scheme for distributed file systems and compactions. By the way, Git has started doing something similar with its [geometric repacking of packfiles](https://git-scm.com/docs/git-repack#Documentation/git-repack.txt---geometricltfactorgt).

**Comment by quark-zju** [comment]
It might be interesting to benchmark it against https://github.com/facebook/sapling/blob/6a84037de9c3e2a8c0576b7418f5abc6f8dde0c6/eden/scm/lib/radixbuf. You can find an example at https://github.com/facebook/sapling/blob/6a84037de9c3e2a8c0576b7418f5abc6f8dde0c6/eden/scm/lib/radixbuf/src/radix.rs#L488.

It's not what Sapling uses today but I think it's quite compelling performance-wise.

**Comment by ilyagr** [comment]
Thanks, @quark-zju , for the pointer! It might be interesting for me to compare.

It seems to be decided that, within reason, the speed of building the index (which happens on every invocation of `jj log`) is more important than the speed of computing prefixes. The prospects of this trie getting merged look pretty dim because of that.

So, the most important question is probably to compare the performance of your radix tree being built to the performance of reading everything into a vector and sorting the vector (which is what we do now).

If the radix tree is close to the same performance, I'd argue for using it. The other problem with the radix tree is that I think it's still GPL.

**Comment by quark-zju** [comment]
The `radixbuf`'s internal is just a flat buffer with an abstracted `resize` operation. So it can be saved to disk and loaded using mmap. I suspect hg is doing something similar nowadays. Sapling does not currently use it because it cannot be updated by appending. Atomically replacing a large index file is undesirable at the scale we support. But the index must be large enough for that to be a problem.

I think the initial implementation can be seen as a derivative work of hg's `revlog.c` so it might have to be GPL.

**Comment by martinvonz** [comment]
> Sapling does not currently use it because it cannot be updated by appending.

We try to avoid even updating by appending, only doing updating by writing new files instead. That makes it possible to merge two repos by letting a distributed file system merge the `.jj/` directories. I'm not sure how much we care to preserve that property, but I'd like to at least try to preserve it if it's not too much work.

> Atomically replacing a large index file is undesirable at the scale we support. But the index must be large enough for that to be a problem.

I think we aim to scale to similar size, so I don't think we would want to write a whole new index file to disk every time. There are lots of other scaling problems we need to fix before jj actually works well in very large repos, but I think it's better to not add more things we need to fix.

That said, we could still use `radixbuf` in memory, but as @ilyagr also said, I'm not sure it'll make enough difference that it matters. It feels like even when displaying the log output for 1k commits, it should easily be fast enough to use binary search.

**Comment by martinvonz** [comment]
By the way, we have talked about possibly using Sapling's IndexedLog, maybe somehow wrapping it so we can preserve the rsync-safety. Things we would like to index:

* commit -> tree of auto-merge parents
* commit (or tree?) -> any paths with conflicts?

I feel like there was something else, but I can't think of anything right now.

**Comment by quark-zju** [comment]
I understand jj's current pursuit of distributed network filesystem compatibility and it is different from what Sapling optimizes for (bounded file count, no repack to maintain log N lookup). To be clear, `radixbuf` does not use filesystem append so it should be compatible with jj. `indexedlog` is the one that uses append and therefore incompatible with jj's current pursuit.

> I think we aim to scale to similar size, so I don't think we would want to write a whole new index file to disk every time. 

There are strategies to avoid writing every time. For example, the radixbuf buffer can be a large but immutable index that only gets updated infrequently. There is a smaller, mutable index that can afford rewriting every time. I think the main difference with @ilyagr's implementation in this PR is that radixbuf supports an efficient "deserialize / load" operation that is simply an O(1) mmap to solve the "build time" problem. I haven't read the latest hg updates but I suspect it is doing something similar.

**Comment by ilyagr** [comment]
To expand on https://github.com/martinvonz/jj/pull/1041#issuecomment-1407160079, I think we could support, in principle, any index format where several files can be efficiently merged without losing the support for distributed file-systems. The index can then be split into a few files, named by their hash. This should work well with distributed systems.

For humongous repositories, it would also be important that this could be done without reading everything into memory.

I'm guessing that's exactly what IndexedLog does, doesn't it?

It also sounds like `radixbuf` does not support it. Neither does my trie, for that matter. (Both can be used in memory, I won't repeat the discussion above regarding this).

Another option that seemed promising was BurntSushi's `fst` crate. It does require loading everything in memory AFAIK (not 100% sure).

**Comment by ilyagr** [comment]
It's time to put this to rest. Some of this discussion might live on in spirit when the index is redesigned.

**Pull request closed without merging**
