### PR TITLE
Use Notepad as default editor on Windows

### PR DESCRIPTION
**Pull request by martinvonz**
Discussed in #2027

# Checklist

If applicable:
- [x] I have updated `CHANGELOG.md`
- [x] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (src/config-schema.json)
- [ ] I have added tests to cover my changes

### CODE REVIEW

**Review by PhilipMetzger — APPROVED** [review]
LG

**Comment by ilyagr** [comment]
I'm slightly worried -- does Notepad wait properly before exiting, so that `jj describe` doesn't exit immediately?

**Comment by PhilipMetzger** [comment]
For my System `notepad.exe` is found under `C:\Windows\system32`. This is a default setup and system32 is always in PATH. See output from %ENV%.
image

**Comment by ilyagr** [comment]
Have you tried this PR? Does jj describe with notepad work?

**Comment by PhilipMetzger** [comment]
No, I haven't tried this PR but when I rebuild JJ from ToT, I'll try it on a local repo

**Comment by ilyagr** [comment]
I guess being a "friend with a Windows computer" is much like being a "friend with a car" :)

**Comment by martinvonz** [comment]
I actually have a Windows computer at home now (and I'm working from home today). I just tried it and it worked! :) I guess because Notepad supports only one open file at a time, it makes sense for it to wait.

**Pull request merged**
