### PR TITLE
Docs: Add note about `jj edit` to Git comparison

### PR DESCRIPTION
**Pull request by bnjmnt4n**
# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [X] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (cli/src/config-schema.json)
- [ ] I have added tests to cover my changes

### CODE REVIEW

**Review by martinvonz — APPROVED** [review]
I know this is marked as a draft, but it already looks good to me

**Comment by bnjmnt4n** [comment]
I've signed the CLA with this email and my GitHub username, clicking the rescan gives me an error 400.

**Comment by martinvonz** [comment]
> I've signed the CLA with this email and my GitHub username, clicking the rescan gives me an error 400.

The check passed now anyway. I have sometimes had to go to an internal page to force a re-scan, but that wasn't  necessary this time.

I've also invited you as a contributor so you can merge PRs yourself once you have approval.

**Comment by bnjmnt4n** [comment]
> I've also invited you as a contributor so you can merge PRs yourself once you have approval.

Thanks! Will being seeing what else I can contribute to!

**Comment by PhilipMetzger** [comment]
FYI, I re-ran the check yesterday so there was no action required :-).

**Pull request merged**
