### PR TITLE
log template: make root commit green instead of bright green

### PR DESCRIPTION
**Pull request by ilyagr**
Bright green really pops on my screen, and I don't think there is a reason for the root commit to be attention-grabbing.

This follows up on https://github.com/martinvonz/jj/pull/2084.

# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (src/config-schema.json)
- [x] I have added tests to cover my changes

### CODE REVIEW

**Review by yuja — APPROVED** [review]
Makes sense since `HEAD@git` is also green. I would also remove `bold` (if you agree.)

**Comment by ilyagr** [comment]
That sounds good to me. @necaqua, would you be OK with non-bold non-bright green?

**Comment by ilyagr** [comment]
Email should be yellow. To distinguish from email without color, I'm still thinking of maybe doing `(root)` instead of `root`.

I don't mind it being the same color as `HEAD@git`. In a way, they are a similar kind of object: a "weird rare branch-like thing that doesn't behave like a branch".

**Comment by necauqua** [comment]
Hm, don't remember why I rejected (root), but I've tried [root] and it was ugly :upside_down_face: I guess parens are fine.

For color sure, that definition makes sense (similar to how in my config I made it look exactly like a change id prefix because it's something I use in a revset most often)

**Comment by martinvonz** [comment]
> Email should be yellow. To distinguish from email without color, I'm still thinking of maybe doing `(root)` instead of `root`.

If we make root a revset function instead (#2095), I guess we might change `(root)` to `root()` :)

**Comment by ilyagr** [comment]
OK, I'll stick with `root` for now. Otherwise we'll be too tempted to switch to Lisp notation for the revset language :stuck_out_tongue:

**Pull request merged**
