### PR TITLE
docs: add link to VisualJJ

### PR DESCRIPTION
**Pull request by sheremetyev**
# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [x] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (cli/src/config-schema.json)
- [ ] I have added tests to cover my changes

### CODE REVIEW

**Review by martinvonz — APPROVED** [review]

**Comment by ilyagr** [comment]
(Optional) Perhaps we should add "Unlike other tools on this page, VisualJJ is not open-source"?

**Review by ilyagr — APPROVED** [review]

**Comment by sheremetyev** [comment]
@ilyagr, I've added a note as you suggested

**Comment by ilyagr** [comment]
Great, thanks!

This LGTM as far as I'm concerned. Usually, we let the author merge the PR. Do you not have that permission? Are you waiting for more comments? If it's the former, I'm happy to merge it for you, or @martinvonz might be able to give you that ability.

**Comment by sheremetyev** [comment]
Thanks @ilyagr! I don't have permissions to merge

**Comment by martinvonz** [comment]
> @martinvonz might be able to give you that ability.

Fixed now

**Pull request merged**
