### PR TITLE
refactor(cargo): unify crate deps under workspace.dependencies

### PR DESCRIPTION
**Pull request by thoughtpolice**
This change is the start of an experiment of mine that *might* prove to be useful one day. To me alone. (But there's no guarantee.) Of that, this singular change out of the bunch, however, might be welcome, maybe, after some bikeshedding. Or not.

Broadly, this unifies the version numbers of all inter-repository crate dependencies under a single root `Cargo.toml` file that specifies `[workspace.dependencies]`. But in order to do that, the `jj-cli` crate has to get kicked out of its home and relegated to a subdirectory so that it can share that benefit with `jj-lib`. That means everything gets pushed down a directory and renamed, so from `./src -> ./cli/src`.

The upshot of this is that there's only a single way to specify any dependency for any crate in the project, and a single way to refer to it: put it in the root Cargo file, then you can just use it as `dep = { workspace = true }` elsewhere. It also reduces a *lot* of the duplication of feature flags between the two crates in practice, and all of them were identical. In the future, there could also more crates with common dependencies (maybe a `jj-inotify` to serve as a lightweight watchman replacement; maybe `jj-web` to have an analog to `jj-web`; `jj-serve` for a push-compatible server, etc.) So a proliferation of this seems pretty undesirable; fixing it now is easier than fixing it later, I'd guess.

This is otherwise transparent to most of the tooling, i.e. uploads and whatnot should all be handled fine. Note that the `optional` dependencies remain in their respective crates; you're required to list *all* potential dependencies, even optional ones, in the top-level Cargo file. Otherwise this doesn't change anything from a user POV.

This is currently failing the `nix build` for some reason, so I'm poking at it. It otherwise *might* be safe and not break things.

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (src/config-schema.json)
- [ ] I have added tests to cover my changes

### CODE REVIEW

**Comment by thoughtpolice** [comment]
Yeah, I think it's mostly a matter of how much pain I'm willing to go through rebasing this over and over. I'm still getting a deterministic failure with `nix build` on my machine with this patch though that I haven't sorted out. It might even be a difference between `nix build` and `nix flake check`, I'm not sure. So for now this might need to go on hold.

**Comment by thoughtpolice** [comment]
We could also split this into a move to `cli/` and then another commit to clean up the Cargo files, which might be better, too.

**Comment by martinvonz** [comment]
> We could also split this into a move to `cli/` and then another commit to clean up the Cargo files, which might be better, too.

Yes, that sounds like a good idea to me.

**Comment by thoughtpolice** [comment]
This has been supersceded by my other PRs recently #1978 and #1991, and the bugs in the test suite that got rattled out were fixed by Martin, too. Closing.

**Pull request closed without merging**
