### PR TITLE
Fix `nix run`

### PR DESCRIPTION
**Pull request by MForster**
Otherwise nix 2.8 and newer will give this error message:

```
>> nix --version; nix run github:martinvonz/jj
nix (Nix) 2.11.1
error: attribute 'defaultApp.x86_64-linux' should have type 'derivation'
```

# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have added tests to cover my changes

### CODE REVIEW

**Review by martinvonz — APPROVED** [review]
I don't know much about Nix but that looks reasonable :) Thanks for fixing.

**Comment by martinvonz** [comment]
@Ralith, this looks very simple, but do you still want to take a look?

**Comment by MForster** [comment]
This first contained two changes, one to `defaultPackage` and one to `defaultApp`. The one that fixes `nix run` is the `defaultApp` change. I've reverted the `defaultPackage` change because it broke the nix build.

**Comment by MForster** [comment]
Ok, I didn't feel comfortable doing this only partially. I've researched a bit more properly how the flake should be updated to the current schema. Here are two context links:

* https://nixos.wiki/wiki/Flakes#Output_schema
* https://github.com/NixOS/nix/issues/5532

PR updated

**Comment by MForster** [comment]
Tested with `nix build`, `nix flake check`, and `nix run`.

**Comment by martinvonz** [comment]
Sorry, I forgot this PR for a day or two. Again, I don't know much about Nix, so I'll just trust you on this.

**Comment by Ralith** [comment]
LGTM.

**Pull request merged**
