### PR TITLE
readme: include link to wiki "Media" page and fix broken changelog link

### PR DESCRIPTION
**Pull request by bnjmnt4n**
# Checklist

If applicable:
- [NA] I have updated `CHANGELOG.md`
- [X] I have updated the documentation (README.md, docs/, demos/)
- [NA] I have updated the config schema (cli/src/config-schema.json)
- [NA] I have added tests to cover my changes

### CODE REVIEW

**Comment by PhilipMetzger** [comment]
This not what I meant in Discord 😄 , I expected that you'd add the new articles to the media section.

**Review by ilyagr — APPROVED** [review]
Seems like a good idea to me. You might want to wait a bit before merging in case others have thoughts.

**Comment by bnjmnt4n** [comment]
> This not what I meant in Discord 😄 , I expected that you'd add the new articles to the media section.

Was there any article in particular to add? I thought we shouldn't overload the readme with lots of articles, but instead Chris's intro and videos + Steve's tutorial would be sufficient. Instead, linking to other articles would allow users to explore different workflows only if they desired.

**Review by PhilipMetzger — APPROVED** [review]
There was no singular article to add, but all of them which were released in the time between march and july. It is fine as is, but I think we should re-discuss our approach to in-repo docs as the wiki isn't indexed by Google.

**Pull request merged**
