### PR TITLE
revset: convert root symbol to function

### PR DESCRIPTION
**Pull request by yuja**
#2095

# Checklist

If applicable:
- [x] I have updated `CHANGELOG.md`
- [x] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (cli/src/config-schema.json)
- [x] I have added tests to cover my changes

### CODE REVIEW

**Review by martinvonz — COMMENTED** [review]
I think it would be nice to allow the `root` symbol for a while, like we do with the `:` operator, if that's not too hard to do. What do you think?

**Comment by yuja** [comment]
> I think it would be nice to allow the `root` symbol for a while, like we do with the `:` operator, if that's not too hard to do. What do you think?

Unlike the `:` operator, I've never used the `root` symbol other than testing jj. So my question is do we use `root` in practice? If that's common enough to insert compatibility shim, maybe we shouldn't change it to a function.

FWIW, I considered adding a hint if `root` couldn't be resolved, but it does actually match a change id `rootvolo...`. So the `root` shim would have to be prioritized than the `rootvolo...` change id.

**Comment by martinvonz** [comment]
> Unlike the `:` operator, I've never used the `root` symbol other than testing jj. So my question is do we use `root` in practice? If that's common enough to insert compatibility shim, maybe we shouldn't change it to a function.

I rarely use it outside of automated and manual testing. Looking back through my shell history, I seem to have used `root::` as a way of writing `all()` without shell escaping and adding it to `tags()` as a way of making `jj log -r 'tags() | root'` look nicer in the git.git (there are many side branches there that are not descendants of any tags). I'm not concerned about either of those cases. My main concern is if people have used `root` in their configs, but it's probably fine to force them to update their configs then. As long as they don't switch back and forth between jj 0.8 and 0.9, which they probably won't. So I think you're right that we don't need the compatibility and warning after all.

> FWIW, I considered adding a hint if `root` couldn't be resolved, but it does actually match a change id `rootvolo...`. So the `root` shim would have to be prioritized than the `rootvolo...` change id.

I think this is maybe the most important reason to change it away from being a symbol - to not have to worry about conflicts with change ids or branches.

**Review by martinvonz — APPROVED** [review]

**Comment by yuja** [comment]
> I seem to have used `root::` as a way of writing `all()` without shell escaping

For this use case, maybe we can add `::` as a short for `root()::visible_heads()`. `..` can also be added (but we might want to adjust `..y` to exclude `root()` for consistency.)

**Pull request merged**
