### PR TITLE
revset: remove 'index lifetime from InternalRevset

### PR DESCRIPTION
**Pull request by yuja**
# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (cli/src/config-schema.json)
- [ ] I have added tests to cover my changes

### CODE REVIEW

**Review by martinvonz — COMMENTED** [review]
I'm not really against this, but it's not an obvious simplification (many added lines of code, but perhaps easier to reason about?), so I'm curious what the goal is. Will it allow some improvements that would be hard to do with the current design?

**Comment by yuja** [comment]
The goal is to remove `unsafe` from `ReadonlyRepo::change_id_index()`. If `RevsetImpl` holds `Arc<ReadonlyIndexSegment>` instead of `&CompositeIndex`, the `'index` lifetime can be removed.

https://github.com/martinvonz/jj/compare/main...yuja:jj:push-ntksqqnrwqpy

We can also rewrite RevWalk, etc. to hold `Arc`, but I don't think abstracting everything makes sense. So the `RevsetImpl` instead pass `&CompositeIndex` to `InnerRevset`s by argument.

**Comment by martinvonz** [comment]
> The goal is to remove `unsafe` from `ReadonlyRepo::change_id_index()`.

Oh, that seems nice. Thanks for working on that. I've already reviewed this PR, so I'll go and approve it now.

**Review by martinvonz — APPROVED** [review]

**Comment by yuja** [comment]
And the last bits to remove `unsafe`. https://github.com/martinvonz/jj/pull/2706

Thanks for reviewing!

**Pull request merged**
