### PR TITLE
cli: Split out ascii template versions and migrate config to toml

### PR DESCRIPTION
**Pull request by algmyr**
This should hopefully unblock #3381.

# Checklist

If applicable:
- [x] I have updated `CHANGELOG.md`
- [x] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (cli/src/config-schema.json)
- [x] I have added tests to cover my changes

### CODE REVIEW

**Comment by martinvonz** [comment]
I would prefer to unblock #3381 by moving keeping the default templates in Rust [as @yuja suggested](https://github.com/martinvonz/jj/pull/3381#discussion_r1542316449). What do you think?

**Comment by algmyr** [comment]
> I would prefer to unblock #3381 by moving keeping the default templates in Rust [as @yuja suggested](https://github.com/martinvonz/jj/pull/3381#discussion_r1542316449). What do you think?

I read that as more a statement of fact by @yuja than a suggestion. But it's one way to do it, sure. Hard coding the defaults in the rust code felt hacky when it was introduced, but was needed because there was the different ascii path.

Would you rather wait and do the move out to toml if/when we get an ascii property to avoid having the duplicate templates?

**Comment by martinvonz** [comment]
> Would you rather keep the defaults hardcoded in the source and do the move out to toml if/when we get an ascii property to avoid having the duplicate templates?

Yes, I would prefer that. It seems unfortunate to introduce a separate template only for a hopefully short time until we support for an `ascii` property.

By the way, another option is that introduce a new type in the templater language for the graph node. I don't know which is better. Maybe there should instead be a `ui.ascii` a general config to get ascii output. We have also talked about making configs accessible in the templating language. Then we would be able to check the `ui.graph.style` config in the template.

**Comment by yuja** [comment]
My current idea is to add some config accessor and `==` operator to templater.

BTW, the log node template could be extracted as an alias, and the hardcoded default could be a shim.
```
node_template_for_key("builtin_log_node_fancy", "builtin_log_node_ascii")
```

**Pull request closed without merging**
