### PR TITLE
Clean up setting of configs in tests

### PR DESCRIPTION
**Pull request by martinvonz**
# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have added tests to cover my changes

### CODE REVIEW

**Review by PhilipMetzger — APPROVED** [review]
Nice cleanup! 
It may be useful to provide some guidance, e.g "we prefer the dotted TOML notation for simple configuration tests" in the future.

**Comment by martinvonz** [comment]
> Nice cleanup!

Thanks :)

> It may be useful to provide some guidance, e.g "we prefer the dotted TOML notation for simple configuration tests" in the future.

Where do you mean that we could document it? In [contributing.md](https://github.com/martinvonz/jj/blob/main/docs/contributing.md)? I feel like this is too detailed to be in there. I don't want that doc to have so much details that no one's going to remember them anyway. I think contributors are likely to look at existing tests, so if those mostly use dotted notation, they'll probably copy that.

**Comment by martinvonz** [comment]
Hey, GitHub, this was merged!

**Comment by martinvonz** [comment]
@PhilipMetzger, can you try approving again to convince GitHub?

**Comment by PhilipMetzger** [comment]
> Where do you mean that we could document it? In [contributing.md](https://github.com/martinvonz/jj/blob/main/docs/contributing.md)? I feel like this is too detailed to be in there. I don't want that doc to have so much details that no one's going to remember them anyway. I think contributors are likely to look at existing tests, so if those mostly use dotted notation, they'll probably copy that.

I'd mention it in a styleguide.md, if we ever provide that. But I agree that most contributors should just look at the tests for now.

**Review by PhilipMetzger — APPROVED** [review]

**Comment by samueltardieu** [comment]
> Hey, GitHub, this was merged!

Again?? Like yesterday, according to https://status.github.com/ everything is fine, but…

**Comment by martinvonz** [comment]
Okay, GitHub, have it your way. For the record, this is actually merged.

**Pull request closed without merging**
