### PR TITLE
Configure nix development shell environment

### PR DESCRIPTION
**Pull request by MForster**
# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have added tests to cover my changes

### CODE REVIEW

**Comment by martinvonz** [comment]
@Ralith, could you take a look at this?

**Comment by ilyagr** [comment]
I'm just curious, why did we decide to update the MSRV to 1.61 in the end?

**Comment by MForster** [comment]
> I'm just curious, why did we decide to update the MSRV to 1.61 in the end?

I'm just stupid. Undoing...

**Comment by ilyagr** [comment]
Oh, I have absolutely nothing against it. I thought there was some feature in 1.61 you wanted to do something cool with. (I'm also fine with not doing it yet).

**Comment by MForster** [comment]
No, I just tested with various MSRV versions that the change does the right thing. Then later I forgot that I had made that change and updated the documentation to match my own inconsistency :-/.

Reverted. Thanks for catching.

**Comment by martinvonz** [comment]
@ilyagr, are you also a Nix user? Are you comfortable reviewing this? Otherwise I'm happy to rubber stamp it.

**Comment by ilyagr** [comment]
No, I don't use `nix`, sorry.

**Review by martinvonz — APPROVED** [review]

**Pull request merged**
