### PR TITLE
git: properly detect default branch

### LINKED ISSUE #30: Figure out why getting default branch from remote is unreliable
Something about how we get the default branch from the remote causes the tests to be unreliable. They have failed on Windows and Ubuntu so far. I have not gotten them to fail on Debian. I suspect it's related to cloning from a local-disk remote. The `Remote::default_branch()` call has failed for me outside of tests in many different ways:

 * `Error { code: -3, klass: 2, message: "could not find '<path to missing included gitconfig file>' to stat: No such file or directory" }`
 * `Error { code: -3, klass: 4, message: "reference 'refs/remotes/origin/main' not found" }`
 * `Error { code: -3, klass: 0, message: "an unknown git error occurred" }`

See e.g. failure on Windows at commit f56262ce85dca2896cb53030e83ceefcaa65029e: https://github.com/martinvonz/jj/runs/3678330357

### PR DESCRIPTION
**Pull request by arxanas**
Might fix #30.

### CODE REVIEW

**Comment by arxanas** [comment]
@googlebot I signed it!

**Comment by martinvonz** [comment]
> The default branch relies on checking the value of `HEAD`. The `empty_git_commit` function updates the ref `refs/heads/main`, but since `HEAD` was never updated to point to that ref, the default branch can't be determined.

Ah, that makes sense! I had not even considered that `git2::Repository::commit()` doesn't set HEAD to the specified ref (but it seems obvious in hindsight). It still passes for me on Debian, so let's see how it goes on other platforms. Thank you!

**Comment by arxanas** [comment]
I neglected to say in the commit message that the error message I was seeing was that `refs/heads/master` was not found, which would certainly be the case if we were looking for `refs/heads/main`.

So where does that default "master" branch name come from if `HEAD` was never set? I recall seeing `init.defaultBranch` in the `libgit2` source code when I was looking into this. @martinvonz I wonder if you've configured `init.defaultBranch` on your Debian machine to `main`, but not elsewhere?

**Comment by martinvonz** [comment]
Aha! We seem to have `init.defaultBranch=main` set in our system-wide configs at work. If I override that to `init.defaultbranch=master` in my `~/.gitconfig`, it does start failing again (without your PR).

I guess that also means that I should try to make the tests not depend on local git configs at all.

**Pull request merged**
