### PR TITLE
log: add -p/--patch option to show diff along with commit meta data

### PR DESCRIPTION
**Pull request by yuja**
like `hg log -p`, which I think is useful with jj.

# Checklist

- [x] I have made relevant updates to `CHANGELOG.md`

### CODE REVIEW

**Comment by martinvonz** [comment]
Thank you so much! There's just that little formatting thing that the CI detected, otherwise all looks good. (I'd be happy to fix that "in flight" but I'm not sure how to do that on GitHub.)

>  show_diff(ui, formatter, opts, ...);  // would be nice if ui could be removed

Yes, I agree. Looks like it's only used for formatting paths now. I'm not sure how we'd remove the need for that.

**Comment by arxanas** [comment]
@martinvonz if the author of the PR selected the option to allow edits from maintainers, then you can actually just check out/edit/push the branch to their repository, which will then be reflected in the PR in the usual way. If you use `gh pr checkout 182`, I think it sets up the right remote for the newly-checked-out branch.

**Comment by martinvonz** [comment]
> @martinvonz if the author of the PR selected the option to allow edits from maintainers, then you can actually just check out/edit/push the branch to their repository, which will then be reflected in the PR in the usual way. If you use `gh pr checkout 182`, I think it sets up the right remote for the newly-checked-out branch.

Ah, thanks, I'll try that.

**Comment by yuja** [comment]
> > show_diff(ui, formatter, opts, ...); // would be nice if ui could be removed
>
> Yes, I agree. Looks like it's only used for formatting paths now. I'm not sure how we'd remove the need for that.

Perhaps format/parse_file_path() can be moved to WorkspaceCommandHelper, and pass `&workspace_command`
around in place of `(ui, repo, workspace_root)`. It will make the helper a little bit more bloated and we might wanna
consider splitting it in future, though.

**Pull request merged**
