### PR TITLE
commit_templater: add self.immutable() method

### PR DESCRIPTION
**Pull request by yuja**
# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (cli/src/config-schema.json)
- [ ] I have added tests to cover my changes

### CODE REVIEW

**Comment by martinvonz** [comment]
@zummenix, FYI, since you were working on indicating this in the graph node.

**Review by martinvonz — APPROVED** [review]
Thank you!

I'm also not sure how to style it.

**Comment by yuja** [comment]
Maybe it's used only in the graph node template?

**Comment by zummenix** [comment]
Nice!

**Pull request merged**
