### PR TITLE
cli: deprecate `--config-toml` in favor of `--config`

### PR DESCRIPTION
**Pull request by martinvonz**
# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (cli/src/config-schema.json)
- [ ] I have added tests to cover my changes

### CODE REVIEW

**Comment by ilyagr** [comment]
Duplicating my comment from Discord, not sure if you saw it:

I was originally thinking of having a simplified syntax with fewer quotes, e.g. `jj --config key string_value_without_quotes`. The syntax would be shared with `jj config set`.  I am still not sure whether or not that's a good idea, but I'm not sure I've fully given up on it yet. 

OTOH, we could decide to give up on that now, I suppose.

**Comment by martinvonz** [comment]
> Duplicating my comment from Discord, not sure if you saw it:
> 
> I was originally thinking of having a simplified syntax with fewer quotes, e.g. `jj --config key string_value_without_quotes`. The syntax would be shared with `jj config set`. I am still not sure whether or not that's a good idea, but I'm not sure I've fully given up on it yet (in fact, right now I can't recall what part of this idea I was doubting. Perhaps having an option with two arguments, but it could also be `jj --config key=string_value_without_quotes`. Perhaps it was the question of how much avoiding shell quoting is really worth).

I did not see that on Discord (until now) but I was thinking the same thing (I think I may have proposed calling the argument `--config-toml` for that reason). I now think it's more confusing than it's worth to have two slightly different ways of setting config. Sounds like you don't feel strongly about it, so let's hear what others think.

**Comment by ilyagr** [comment]
For the sake of history, and to explain my attachment to it, I think it was my idea; we discussed it in https://github.com/martinvonz/jj/pull/703#discussion_r1014587705. I'm indeed not sure what's best to do now.

**Comment by yuja** [comment]
I'm for this change, but I also like the idea of simpler less-quoting form.

Suppose `--config-toml "$(< config.toml)"` is rarely used, maybe we can drop support for full document parsing, and add simpler `key=value` parsing rule later? Here `key` must be dotted TOML path, and `value` can be either TOML value or string.

**Comment by martinvonz** [comment]
> Suppose `--config-toml "$(< config.toml)"` is rarely used, maybe we can drop support for full document parsing, and add simpler `key=value` parsing rule later? Here `key` must be dotted TOML path, and `value` can be either TOML value or string.

That makes sense to me. If it's the same format for keys and values as in `jj config set` (as I assume it would be), that seems like it should be consistent and good enough.

**Comment by arxanas** [comment]
FWIW I do find the `-toml` suffix to gently remind me of the exact syntax... I may very well forget that I can't just write `--config=key=value` without it. Actually, I think I would frequently get a syntax error the first time I just issued commands of the form `--config=key=value` and then have to go back and quote it every time.

I do like the fact that I can, at least in principle, provide structured list arguments (I guess to something like an editor invocation?) but maybe it's a rare case in practice. In the hypothetical shorthand configuration option, probably the more common interesting case is distinguishing `true` from `"true"`.

Although the flag is a little clunky at present, is it really causing problems for people? What happens if we just leave it?

**Comment by ilyagr** [comment]
> Suppose --config-toml "$(< config.toml)" is rarely used, maybe we can drop support for full document parsing, and add simpler key=value parsing rule later? 

I agree that "$(< config.toml)" is not great, especially on Windows. If we get rid of it, though, we still need some way to specify complicated extra config on the command line.

So, we could support `--config-from filename`. In fact, I think that would be good regardless of whether we change the behavior of `--config-toml`. I'm not certain about the name, other alternatives that come to mind are `--extra-config-file`, `--extra-toml-config-file`, maybe `--config-file`.

The other option I considered is to allow something like `--config imports.overrides=filename`, but that opens several new cans of worms, and I don't think it's better.

As for whether we should have a simplified `--config` only, a simplified `--config` and `--config-toml`, or `--config` with TOML syntax, there seems to be advantages and disadvantages to each; I don't have a clear preference at the moment.

**Comment by martinvonz** [comment]
Are people more comfortable with the change if we first add support for simplified syntax as Yuya suggested before we rename the argument? I think we should make `jj --config[-toml]` and `jj config set` consistent, both w.r.t. name and w.r.t to syntax. I'm fine with doing it in either order, but maybe others prefer to allow the simplified syntax first and then rename the argument.

**Comment by yuja** [comment]
> Are people more comfortable with the change if we first add support for simplified syntax as Yuya suggested before we rename the argument? I think we should make `jj --config[-toml]` and `jj config set` consistent, both w.r.t. name and w.r.t to syntax. I'm fine with doing it in either order, but maybe others prefer to allow the simplified syntax first and then rename the argument.

I'm fine with either way. Perhaps, it depends on whether we'll drop support for `--config-toml=$(< full_toml_doc)` immediately? It would be messier if `--config` supported all of the `toml_key_value|toml_key_bare_string|toml_document` forms.

**Comment by emilazy** [comment]
FWIW I’m fine with needing to use TOML syntax, but the `--config-toml` name always makes me expect that it takes a path to a `.toml` file, so I definitely support changing the name if nothing else.

**Pull request closed without merging**
