### PR TITLE
cli: move: Add -f/-t for --from/--to to `jj move`

### PR DESCRIPTION
**Pull request by poliorcetics**
I find myself often using `jj move` when working and having shorthands for `--from/--to` would be very useful

# Checklist

If applicable:
- [x] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (cli/src/config-schema.json)
- [x] I have added tests to cover my changes (modified existing one)

### CODE REVIEW

**Comment by arxanas** [comment]
Be advised that `-f` may conflict with a future `--force` option, should we choose to add one in the future.

**Comment by thoughtpolice** [comment]
> Be advised that `-f` may conflict with a future `--force` option, should we choose to add one in the future.

I almost wonder if we want to call them `--source` and `--dest` instead, to match what we do in `jj rebase`. `-s` and `-d` are relatively uncommon and it would be a little more "symmetrical." Just a thought.

**Comment by yuja** [comment]
This seems also related: https://github.com/martinvonz/jj/discussions/2882

**Comment by poliorcetics** [comment]
I can rename to `--source/--dest` and associated shorthands if preferred

**Comment by martinvonz** [comment]
> I can rename to `--source/--dest` and associated shorthands if preferred

I think this PR is good as is. Whether we rename the flags seems like a separate discussion that shouldn't block this.

> I almost wonder if we want to call them `--source` and `--dest` instead, to match what we do in `jj rebase`. `-s` and `-d` are relatively uncommon and it would be a little more "symmetrical." Then we would keep `-f` free. Just a thought.

`--from` and `--to` also seem very symmetrical, don't they? We also have `jj diff` to compare to, and `-s`/`-d` seem to make less sense there. That said, I'm not completely against naming these flags more in line with `jj rebase` than `jj diff`.

> This seems also related: https://github.com/martinvonz/jj/discussions/2882

Yes.

**Review by martinvonz — APPROVED** [review]

**Review by thoughtpolice — APPROVED** [review]

**Comment by poliorcetics** [comment]
Fixed the conflict in the changelog

**Pull request merged**
