### PR TITLE
cli: don't abandon non-discardable old wc commit by import_git_head()

### PR DESCRIPTION
**Pull request by yuja**
#3747

# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (cli/src/config-schema.json)
- [x] I have added tests to cover my changes

### CODE REVIEW

**Review by bnjmnt4n — APPROVED** [review]
LGTM, I can't think of any downsides to this change. Hopefully it makes the colocation experience much better.

**Comment by ilyagr** [comment]
I tried out this PR in my copy of `jj` and ran into the bug again. With this PR, the bug created a single divergent commit instead of the mess it made before, so I think the PR definitely improved the outcome quite a bit. In fact, the only remaining problem in this example seems to be that the working copy and its parent commit were not abandoned.

Here's the repo (50MB): https://ilya.gr/share/jj-bug-2024-05-24.tar.gz

I definitely agree with the direction of this PR -- the "best" fix for the bug would be that the rules of the resolution of concurrent operation be such that any partial git import from a concurrent operation cleanly merges with the main operation and does not affect the outcome. This is easier said than done, of course.

**Comment by yuja** [comment]
> With this PR, the bug created a single divergent commit instead of the mess it made before,

I haven't inspected the op log, but I think that's because an intermediate `HEAD` state was captured by background process and checked out (i.e. created independent wc commits.) I don't think it can be "fixed" without introducing wider lock.

Maybe diverged wc pointers could be merged somehow, but I have no idea if that will work.

**Comment by yuja** [comment]
fwiw, for background viewer processes, https://github.com/martinvonz/jj/issues/2562#issuecomment-1804348449 might help.

**Comment by yuja** [comment]
> Here's the repo (50MB): https://ilya.gr/share/jj-bug-2024-05-24.tar.gz

Filed as https://github.com/martinvonz/jj/issues/3754

**Comment by ilyagr** [comment]
> fwiw, for background viewer processes, https://github.com/martinvonz/jj/issues/2562#issuecomment-1804348449 might help.

Very good point. We could even have an option to forbid more than one instance of `jj` from running without the `--do-not-commit-transaction` option, though this would go against lofty concurrency goals.

**Pull request merged**
