### PR TITLE
Add ui.unique-prefixes and git.auto-local-branch to config schema

### PR DESCRIPTION
**Pull request by dbarnett**

### CODE REVIEW

**Review by martinvonz — APPROVED** [review]
Thanks for fixing. I'll try to remember to keep this file updated in the future.

**Comment by samueltardieu** [comment]
> Thanks for fixing. I'll try to remember to keep this file updated in the future.

Shouldn't we make it an error to try to retrieve a key which is not in the schema? If we need dynamically built values at some point we can then add a flag saying "this won't be in the schema" or even "this corresponds to this key in the schema".

**Comment by martinvonz** [comment]
> Shouldn't we make it an error to try to retrieve a key which is not in the schema?

You mean by using `config-schema.json` as the source of truth? I think we were planning to generate that file (`jj debug config-schema`, perhaps) based on some internal definition in the code, but it sounds reasonable to use it as source of truth until we get there. FYI, we want to be able to extend the config schema (wherever it's defined) so custom binaries can add their own configs.

**Comment by dbarnett** [comment]
Right, I have some thoughts about how to make it easier to catch mismatches. For now I think it's fine to just patch them up as we notice them (or feel free to ping me to incorporate updates... it can be a little fiddly figuring out the jsonschema mechanics for some things).

> Shouldn't we make it an error to try to retrieve a key which is not in the schema?

Yeah, #1153 suggested a warning, which would be useful if it could be done gracefully. The config schema wouldn't always be in lockstep with the binary (after all, config files hang around for a while and it's nice if there's some graceful phasing-out of older options), but having a common source-of-truth for most of it would be useful, and probably we'd do that by flipping the `jj debug config-schema` to *generate* the schema informed by its own internal representation. But still, for it to work well for jj users out of the box I think we'd need to submit a copy to https://github.com/schemastore/schemastore and just try to update that as we notice it's stale (or maybe someday automate the PR creation?).

**Comment by samueltardieu** [comment]
I was proposing using it as a source of truth for what can be queried from the `jj` program. Of course the configuration files themselves could contain unrecognized keys. Maybe the `Config` object could contain the schema to use (or `None` to prevent checks), so that an extended schema could be loaded by an extension as well.

**Comment by dbarnett** [comment]
Yeah, still haven't decided the exact mechanism but at any rate we're all agreed we want to unify it. Feel free to create an FR for unifying schema SoT and we can discuss more specifics & trade-offs.

**Pull request merged**
