### PR TITLE
Reword paragraph about jj and other VCS in README

### PR DESCRIPTION
**Pull request by ilyagr**
Fixes two pedantic issues with this paragraph:

* "either" describing more than two things.

* I am not an expert, but I suspect that Pijul supports "automatic rebase".

### CODE REVIEW

**Comment by martinvonz** [comment]
> I am not an expert, but I suspect that Pijul supports "automatic rebase".

Neither am I, but I think it's at least technically correct :) I suspect the answer is that the operation doesn't make sense in Pijul (or Darcs). IIUC, patches don't have any order in Pijul and Darcs, other than an order that can be inferred by which other patches they apply to, or something like that. Is that your impression too?

**Comment by martinvonz** [comment]
Btw, I doesn't seem that the author of Pijul has an account here, but maybe @jneem (who has an old fork of Pijul here) can help clarify how it works.

**Comment by jneem** [comment]
I'm definitely not up-to-date on the latest developments, but from what I remember patches in Pijul have dependencies on other patches. These dependencies are inferred by the diff tool when the patch is created.

The partial order implied by these dependencies tends to be much weaker than the order imposed by other VCSes, which seems to reduce the need for rebasing: you can just apply all the patches in any order and the dependencies will automatically be resolved. I do think that there are some potential use-cases for rebasing (especially `rebase -i` in git) that aren't covered by this, and I don't know if Pijul has a tool that covers these other use cases.

**Comment by ilyagr** [comment]
> Is that your impression too?

Yes, that's about what I understand as well, @martinvonz. 

I looked into it a tiny bit. According to Pijul's manual, [rebase is the same as merge there](https://pijul.org/manual/workflows/channels.html?highlight=rebase#what-is-a-channel). I was also surprised to find that Darcs [has a rebase operation](http://darcs.net/Using/Rebase). I'm not sure what that does.

> Neither am I, but I think it's at least technically correct :)

In this case, I think that's a pretty tenuous argument. As far as I can guess, Pijul will not require the user to do anything to "rebase" in every case where `jj` rebases automatically. However, involving more knowledgeable people as you did is probably a good idea if you want to word this perfectly.

As always, feel free to treat this as a bug report for a minor bug, and fix it (or not) however you see fit.

**Comment by martinvonz** [comment]
> In this case, I think that's a pretty tenuous argument. As far as I can guess, Pijul will not require the user to do anything to "rebase" in every case where `jj` rebases automatically.

Yes, I agree. I just thought it was close enough that it was worth the simpler way of explaining it. I'd prefer to switch back to the old form and replacing "not found in either of them" by "not found in most of them" to keep it simple. Does that sound okay?

**Comment by ilyagr** [comment]
That sounds fine to me.

**Review by martinvonz — APPROVED** [review]
Thanks!

**Pull request merged**
