### PR TITLE
cargo: downgrade off of yanked version of `textwrap`

### PR DESCRIPTION
**Pull request by martinvonz**
# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)

### CODE REVIEW

**Review by Ralith — APPROVED** [review]

**Comment by martinvonz** [comment]
@mgeisler, simply upgrading our own version of `textwrap` is not enough because we also depend on `criterion` 0.4.0, which depends on `clap` 3.1, which depends on the yanked `textwrap` 0.15.1. What should we do? Would it make sense to release a `textwrap` 0.15.2 that's the same as 0.15.0, so libraries like `clap` don't need a new release to work with an unyanked `textwrap`?

**Comment by mgeisler** [comment]
> Would it make sense to release a `textwrap` 0.15.2 that's the same as 0.15.0, so libraries like `clap` don't need a new release to work with an unyanked `textwrap`?

Yeah, that might be the best solution... See also https://github.com/clap-rs/clap/issues/4418 and https://github.com/mgeisler/textwrap/issues/453.

**Comment by martinvonz** [comment]
@Ralith, I solved this by instead downgrading `clap` and `textwrap`. See the updated commit message for explanation. Can you take another look?

**Comment by martinvonz** [comment]
> @Ralith, I solved this by instead downgrading `clap` and `textwrap`. See the updated commit message for explanation. Can you take another look?

There's actually a `textwrap` 0.15.2 available now (thanks, @mgeisler!), so we could instead upgrade to that. I don't think it really matters since our `clap` 3 dependency is just used by `cargo bench` (IIUC). Let me know if you prefer that I upgrade.

**Comment by martinvonz** [comment]
Actually, with the new 0.15.2 out, the Dependabot upgrade of `textwrap` from 0.15.1 to 0.16.0 in #670 also included an upgrade from 0.15.2 for the transitive dependency, so I'll just drop this PR.

**Pull request closed without merging**
