### PR TITLE
feat(cargo): improve --release binary size

### PR DESCRIPTION
**Pull request by thoughtpolice**
Summary: On x86_64-linux, these options reduce the total number of bytes in the `jj` binary by 40 percent, from 16MiB to 9.8MiB, while having relatively minimal impact on build time, going from 58s to 1m15s.

While `strip=debuginfo` is already the default, `codegen-units=1` is doing all the work here, and seems to have a rather miraculous effect despite not meaningfully hurting compile time too much for me at least. This actually will probably improve performance in some cases too, but it's likely hard to quantify.

Ultimately, with or without this change, the dominant entity taking up most of the compile time for the whole project is `jj-lib` and `jj-cli` crates. A `--timings` report with Cargo indicates almost all dependencies (on my machine) compile within 30s whether or not this change is in play, so the remaining time is all on us.

Various other changes, such as using `opt-level=z` or `lto=thin`, had no real visible effect. `lto=fat` was pretty successful, reducing total bytes by over 50% (7.8MiB), but at a nearly 2x link-time cost.

It *might* be worth exploring if something like `lto=thin` could improve performance since it didn't meaningfully impact compile time or size any further, but that's TBD.

Note: these numbers were performed with a wiped `target/` directory after each run, and so all dependencies were compiled from scratch, on my 12-core Ryzen 5600X.

Change-Id: Ioyoulrmtwxypsrwwwysyylvmqxzttkmn

# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (src/config-schema.json)
- [ ] I have added tests to cover my changes

### CODE REVIEW

**Comment by ilyagr** [comment]
Nice! On my machine, it goes from 19M to 12M (not sure why it's 3M larger than on your machine).

I'll wait to approve, perhaps somebody with more experience will chime in.

**Comment by thoughtpolice** [comment]
Maybe different `rustc` and `cargo` versions? Mine are provisioned from nix via `direnv`:

```
austin@GANON:~/src/jj$ cargo --version && rustc --version
cargo 1.64.0 (387270bc7 2022-09-16)
rustc 1.64.0 (a55dd71d5 2022-09-19)
```

**Comment by ilyagr** [comment]
My guess is that nix (whether by default or because of the flake config) links something dynamically that is linked statically for me.

**Comment by thoughtpolice** [comment]
Possibly. I also changed my toolchain to the latest stable rustc (1.70.0 as of this writing) and the improvement was technically even *better*: from 17MiB to 9.7MiB, and atest compile went from 1m19s to 1m30s, so the overall delta was proportionally smaller &mdash; though `rustc` has overall gotten slower it seems :( 

I'll file a separate change for the `devShell` in the flake to use the latest stable. `ldd` output for reference.

```
austin@GANON:~/src/jj$ ldd ./target/release/jj
        linux-vdso.so.1 (0x00007fff287df000)
        libzstd.so.1 => /nix/store/wcycj7mjx18d1d9iyzik16fag9pzcznc-zstd-1.5.5/lib/libzstd.so.1 (0x00007f646f472000)
        libgit2.so.1.6 => /nix/store/xx9jj8915adw02mllr216srgy15dc32x-libgit2-1.6.4/lib/libgit2.so.1.6 (0x00007f646f330000)
        libssh2.so.1 => /nix/store/xr0rc6y719iyks4lq5xba0g2inqng1zy-libssh2-1.11.0/lib/libssh2.so.1 (0x00007f646f2ea000)
        libssl.so.3 => /nix/store/ii5lq0igwk9xpq16s98yqswsgr1dbfi2-openssl-3.0.9/lib/libssl.so.3 (0x00007f646f23d000)
        libgcc_s.so.1 => /nix/store/75622q2wranjp6zl81ldq5j54s788dqz-gcc-12.3.0-lib/lib/libgcc_s.so.1 (0x00007f646f21a000)
        libm.so.6 => /nix/store/wpgrc564ys39vbyv0m50qxmq8dvhi7cc-glibc-2.37-8/lib/libm.so.6 (0x00007f646f13a000)
        libc.so.6 => /nix/store/wpgrc564ys39vbyv0m50qxmq8dvhi7cc-glibc-2.37-8/lib/libc.so.6 (0x00007f646ef54000)
        /nix/store/wpgrc564ys39vbyv0m50qxmq8dvhi7cc-glibc-2.37-8/lib/ld-linux-x86-64.so.2 => /nix/store/wpgrc564ys39vbyv0m50qxmq8dvhi7cc-glibc-2.37-8/lib64/ld-linux-x86-64.so.2 (0x00007f646fe88000)
        libcrypto.so.3 => /nix/store/ii5lq0igwk9xpq16s98yqswsgr1dbfi2-openssl-3.0.9/lib/libcrypto.so.3 (0x00007f646ead8000)
        libhttp_parser.so.2.9 => /nix/store/5bx2jmwav2ddbjx9009l1s5bzw0s90gn-http-parser-2.9.4/lib/libhttp_parser.so.2.9 (0x00007f646eacb000)
        libpcre.so.1 => /nix/store/cg0f1vdqgfx78n8rn60bzrbl2lhvh5y8-pcre-8.45/lib/libpcre.so.1 (0x00007f646ea51000)
        libz.so.1 => /nix/store/s9zl0rv45yc3ymx61q6n97c3l7196pq4-zlib-1.2.13/lib/libz.so.1 (0x00007f646ea32000)
        librt.so.1 => /nix/store/wpgrc564ys39vbyv0m50qxmq8dvhi7cc-glibc-2.37-8/lib/librt.so.1 (0x00007f646ea2d000)
        libdl.so.2 => /nix/store/wpgrc564ys39vbyv0m50qxmq8dvhi7cc-glibc-2.37-8/lib/libdl.so.2 (0x00007f646ea28000)
        libpthread.so.0 => /nix/store/wpgrc564ys39vbyv0m50qxmq8dvhi7cc-glibc-2.37-8/lib/libpthread.so.0 (0x00007f646ea23000)
```

**Comment by ilyagr** [comment]
Here's my `ldd` output. It's clearly different.

```
        linux-vdso.so.1 (0x00007ffc00efb000)
        libssl.so.3 => /lib/x86_64-linux-gnu/libssl.so.3 (0x00007f1d476ef000)
        libcrypto.so.3 => /lib/x86_64-linux-gnu/libcrypto.so.3 (0x00007f1d46600000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f1d476d0000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f1d476b0000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1d46b21000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1d4641f000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f1d477b2000)
```

**Comment by thoughtpolice** [comment]
Yes, and actually, the release executables are statically linked with musl, so I wonder if they'll see the greatest benefit of all. I'll try to get around to testing it; but I suspect this is probably a pretty decent win across the board, at this rate...

**Comment by ilyagr** [comment]
I actually use musl myself and tried it. This PR makes the statically linked musl executable go from 22M to 15M on my machine.

**Comment by thoughtpolice** [comment]
Yeah, so it looks like the roughly ~7MB of saved space in the Rust code is actually about constant across the toolchain versions and C library choices. I'd have to test macOS and Windows separately.

The best advantages would come from being able to LTO across the Rust/C boundary using a compatible version of Clang but I'm sure that will expose lots of fun issues and I'm not sure if Cargo is up to the task.

For reference: `git` is 3.8MiB on my machine, and only dynamically links to `libc`.

**Comment by ilyagr** [comment]
I wonder, do you happen to know a way to try out `lto=fat` without changing `Cargo.toml`, just by adding some `cargo build` argument? I tried

     RUSTFLAGS="-C lto=fat" cargo build --release

but got some build errors along the lines of

    error: options `-C embed-bitcode=no` and `-C lto` are incompatible

**Comment by thoughtpolice** [comment]
I think we can do `CARGO_PROFILE_RELEASE_LTO=fat` according to https://doc.rust-lang.org/cargo/reference/environment-variables.html#configuration-environment-variables, which seems to work. I just tested it and am re-building with this patch now. I'll make some updates to this PR and also update the Nix expression; we can get it in for 0.8.0 perhaps

**Comment by ilyagr** [comment]
> I think we can do `CARGO_PROFILE_RELEASE_LTO=fat` according to https://doc.rust-lang.org/cargo/reference/environment-variables.html#configuration-environment-variables, which seems to work.

That saves about another 1MB on my machine, at the cost of veeery slow linking. Not sure what's different from your setup.

**Comment by martinvonz** [comment]
> My guess is that nix (whether by default or because of the flake config) links something dynamically that is linked statically for me.

Yes, that's probably thanks for #1577

**Comment by ilyagr** [comment]
I guess my only worry is whether this makes `jj` run slower. If I understand correctly, this merely makes the linker work harder and shouldn't measurably affect runtime speed, but I have no experience with these kinds of optimization.

**Comment by thoughtpolice** [comment]
So `codegen-units` is sort of an LLVM detail, but it basically means "how many modules do you process in parallel" and by setting it to 1, you serialize that task, but allow potentially improved optimization. It's not actually a linker flag, but a flag to rustc that it uses at the crate level (so in some sense rustc is kind of a linker because it does intra-crate optimizations and stuff, but you get my drift.) Fat LTO just defers even more optimization to link-time when `ld` is invoked and is actually *probably* a very very small improvement as well on that note, though it does take a lot more memory and time. It's probably worse the slower your DRAM and HDD speed are, too, I guess. ThinLTO is a more scalable version of FatLTO but doesn't have all the performance benefits.

Overall I suspect the performance benefit is probably quantifiable at large scale, but the binary size benefits were my main motivation. Luckily I think you could test all these variations pretty well. The most important thing is that every release and build variation undergoes proper testing, I think.

**Comment by yuja** [comment]
> While `strip=debuginfo` is already the default

I don't think it's the default, and also affects custom profiles that inherit `"release"` like
```toml
[profile.release-with-debug]
inherits = "release"
debug = true
```

> while having relatively minimal impact on build time, going from 58s to 1m15s.

Just a comment. I think this change will impact on incremental build since we only have two crates to compile (ignoring dependencies.) I don't know if people care for incremental build time of release configuration, though.

**Comment by thoughtpolice** [comment]
> I think this change will impact on incremental build since we only have two crates to compile (ignoring dependencies.) I don't know if people care for incremental build time of release configuration, though.

Good point to mention. I wonder what profile people usually use when testing their own `jj` copies? I didn't touch debug here since editing in your LSP-aware editor is much more sensitive to that I think.

**Comment by yuja** [comment]
> I wonder what profile people usually use when testing their own `jj` copies?

I think most people use `dev` profile. I occasionally build with custom `release-with-debug` profile to measure performance, which is already slow (enough to start web browsing) and I wouldn't mind if the incremental build time increased ~20%.

**Comment by necauqua** [comment]
> on my 12-core Ryzen 5600X

on my 12-core Ryzen 3900XT this happens:
image

but since this is a release build it's fine if in turn we get a smaller binary I guess (although `nix profile update` from bleeding main will take 2x the time for me :upside_down_face:)

**Comment by thoughtpolice** [comment]
FWIW, I thought about looking into Cachix for Nix users, actually, but frankly I don't think it's worth it at the moment, as a 2-3min clean build is tolerable enough, and there are only a couple people actively developing/installing `jj` with Nix anyway (I do `nix profile upgrade` for `jj` once every couple days unless a bugfix I want happens). Ideally with a more recurring and automated release process as discussed in Discord, this would matter less too; they'll just get binaries from upstream Nixpkgs anyway. The Nix build currently doesn't handle macOS either, which is another nit.

Unfortunately, I think there are probably very few remaining "trivial, no effort" wins for build time remaining after #1837 was merged; anything that can do much better will become increasingly invasive (shed cargo deps, carefully reduce monomorphizing, more radical build engineering.)

**Comment by ilyagr** [comment]
Is there any benefit to keeping debug information in the release build, @yuja?  If you are fine with it, you can just approve this.

Does the debug info take up a lot of space, @thoughtpolice?

I'm pretty happy with `codegen-units=1`; I don't make release build often and I *do* store jj binaries in a Github LFS repo with 1GB size limit.

**Comment by thoughtpolice** [comment]
`split = "debuginfo"` saves about 3MiB for me (16MiB -> 13MiB), so it's about half the win. There's two parts to the debuginfo, the chunky DWARF bits that contain stuff like source text, and the symbol table with names in it; `debuginfo` only strips the first of those but not the second, because the symbol table is used to print out names when a panic happens. Throwing away the symbol table is really not worth it &mdash; even though it's often surprisingly big (because mangled, monomorphized rust names are often really long, just like C++)

In a better world, we could actually keep both using something like split-dwarf debug info, so every release or build could get a split dwarf file to go along with it. Then things like coredumps on the statically linked binary would remain really useful, for instance, and you could do post-mortem stuff. But the problem is I think split dwarf is still only kinda-sort-of-variously-supported in all sorts of debugging tools, while DWARF mostly works. And in Rust a lot of SIGSEGV-related problems are eliminated by the typechecker

**Comment by yuja** [comment]
> Is there any benefit to keeping debug information in the release build, @yuja?

I thought it would break backtrace, but with ld or lld, symbol names are printed. If the linker is mold, symbols appear to be lost.

My `--profile=release-with-debug` use case is for performance analysis. This PR affects custom profiles inheriting release, but this problem can be adjusted by overriding the `strip` configuration.

Honestly, I have no idea why binary size matters. `codegen-units=1` will improve the runtime, but debug sections wouldn't be mapped anyway.

**Comment by ilyagr** [comment]
Perhaps we should merge this and include a correct version of the `release-with-debug` profile in the `Cargo.toml` either in this PR or a separate one? After that PR, setting that up `release-with-debug` will become less straightforward.

I think we do care about backtraces. It's a bit unfortunate about the `mold` linker, but as far as I understand `mold` makes more sense for debug builds than release builds (I've heard it's fast; I haven't heard anything about it creating a better binary, though I didn't listen very carefully).

In terms of compilation speed, I think we'll notice if `codegen=1` starts causing problems; then our release build will become much slower than the debug build.

I would benefit from this slightly, and I'm leaning towards merging this as is, but I'm OK with merging just the `codegen=1` part or nothing.

**Comment by thoughtpolice** [comment]
FWIW, I think mold will only bring visible benefit in much larger final exes, which are the case where A) debug sizes get really large and as a result B) production non-debug sizes get reasonably large, think a +100MiB release binary. It's good in both cases, but we're pretty far away from that.

I did try using mold myself to cut down on the build time increase seen here, and didn't really notice any major improvement from any change I could make. Ultimately the vast majority of compile time in all the cases is just spent on code generation for both `jj-lib` and `jj-cli` from what I can see.

**Comment by yuja** [comment]
Well, I don't have strong opinion against stripping debug sections. I just mean it wouldn't affect runtime memory footprint (unlike `condegen-units` which shrinks the text section?)

> I think mold will only bring visible benefit in much larger final exes

Yep. I just configured it globally and found debug symbols are somehow lost.

**Review by ilyagr — APPROVED** [review]
It seems that nobody has strong feelings against these options for the moment. Let's try it out, and please be vocal if you develop stronger feelings against them. We can always undo it.

**Comment by ilyagr** [comment]
Also, thanks @thoughtpolice !

**Comment by yuja** [comment]
> If the linker is mold, symbols appear to be lost.

Just for reference, it's a trivial bug in mold.
https://github.com/rui314/mold/pull/1038

**Pull request merged**
