### PR TITLE
tests: fix mtime flakiness in git gc tests

### PR DESCRIPTION
**Pull request by yuja**
#3537

@thoughtpolice can you try this patch? I cannot reproduce the problem reliably at my end.

# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (cli/src/config-schema.json)
- [ ] I have added tests to cover my changes

### CODE REVIEW

**Comment by thoughtpolice** [comment]
I just blindly ran `for x in $(seq 1 20); do cargo nextest run --workspace; done` since in my experience the failure rate is higher than ~5%, and unfortunately after 10-15 runs it failed again, with a slightly different LHS/RHS:

```
--- STDOUT:              jj-lib::runner test_git_backend::test_gc ---

running 1 test
git version 2.44.0
test test_git_backend::test_gc ... FAILED

failures:

failures:
    test_git_backend::test_gc

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 315 filtered out; finished in 0.32s


--- STDERR:              jj-lib::runner test_git_backend::test_gc ---
thread 'test_git_backend::test_gc' panicked at lib/tests/test_git_backend.rs:154:5:
assertion `left == right` failed
  left: {CommitId("395234a1c7b881d22499564b5d2196203ac6d782"), CommitId("ae36ec61acbca7209121052dda43f9ca9db90817")}
 right: {CommitId("ae36ec61acbca7209121052dda43f9ca9db90817"), CommitId("7231fd316deb9d5c8f479e625dba6a9004dddc30"), CommitId("395234a1c7b881d22499564b5d2196203ac6d782")}
```

Maybe 1 second isn't enough? I haven't spent time looking at the test since I figured you'd have a better idea anyway :)

**Comment by yuja** [comment]
>   left: {CommitId("395234a1c7b881d22499564b5d2196203ac6d782"), CommitId("ae36ec61acbca7209121052dda43f9ca9db90817")}
>  right: {CommitId("ae36ec61acbca7209121052dda43f9ca9db90817"), CommitId("7231fd316deb9d5c8f479e625dba6a9004dddc30"), CommitId("395234a1c7b881d22499564b5d2196203ac6d782")}

Ok, this appears to be an mtime problem in gix. `GitBackend::gc()` first updates refs internally by using `gix` API, then spawns `git gc` process. If `git gc` quickly rewrites the packed refs, `gix` can't detect the change because `mtime` is the same. Perhaps, we can get around the problem by reloading the refs store or gix repo.

**Comment by yuja** [comment]
Updated tests to not rely on in-memory cache. I've tested the change on old ext3 image (of 1sec timestamp accuracy) where the problem can be ~100% reproduced.

**Review by martinvonz — APPROVED** [review]
Thanks for fixing.

**Review by thoughtpolice — APPROVED** [review]
My test of 20 runs went through fine, thanks a lot!

**Pull request merged**
