### PR TITLE
copy refs/heads to `remote_targets["git"]` to remove special case for `@git` branches

### PR DESCRIPTION
**Pull request by yuja**
# Checklist

If applicable:
- [x] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (cli/src/config-schema.json)
- [x] I have added tests to cover my changes

### CODE REVIEW

**Review by martinvonz — APPROVED** [review]
Thank you! I see why this had to wait for `remote_branches()` to not be used in the default log revset now :)

**Comment by ilyagr** [comment]
Perhaps we should wait and merge this after we cut a new release? That would also conveniently give me time to maybe have a look.

But if you prefer to do it quicker, that's OK too.

**Comment by yuja** [comment]
> Perhaps we should wait and merge this after we cut a new release?

Sure. I'll implement new import/export/undo behavior on top of these patches, so please let me know early if you find a fundamental problem in this PR.

**Comment by yuja** [comment]
I'm gonna merge this. I'll send a follow up if there are things to fix.

**Comment by ilyagr** [comment]
Yes, sorry, I'm still busy with non-jj things. I'm hoping to become more free in a couple of weeks, I guess I'll try to play catch-up then.

**Pull request merged**
