### PR TITLE
fix(config): by default, render git refs as green instead of magenta

### PR DESCRIPTION
**Pull request by thoughtpolice**
Summary: Someone on Discord mentioned that while using branches, they could switch between branches like `m1` and `main`, but not `HEAD@git`, even though it was color coded the same and located right next to the other branch names in the default `jj log` output.

This confused me too at first, until I realized `jj` was telling me that the given commit was the `HEAD` reference in the colocated git repo. Let's just color these references differently in the default schema, to try and hint that these aren't the same. `bright green` is arbitrary, but helps stand out; and `green` was only picked because both it and `git` start with "g".

# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`

### CODE REVIEW

**Comment by necauqua** [comment]
> they could switch between branches like

The thing is that you do not "switch between branches" in jj, you create a new child working copy commit off of some commit that you specify with a revset reference.

So it would make total sense if HEAD@git was such a reference, so that everything would just work that the intuition suggests 🤷 - see me citing myself from discord in https://github.com/martinvonz/jj/issues/1843#issuecomment-1629858016

**Comment by thoughtpolice** [comment]
> The thing is that you do not "switch between branches" in jj

Sure, but we're splitting hairs here in a sense; you can replace "switch between branches" with "checkout a new working copy commit based on a named reference" and more or less nothing else changes. I don't think the spirit of what the user is achieving is pretty clear here.

Even *if* we do allow `HEAD@git` for revset syntax (which I'm not opposed to!) I also think there is to some extent some merit between distinct `@git` remotes and otherwise typical named references since they don't behave the same &mdash; for instance, you're never going to see it in `jj git remote list` nor in a non-colocated repository.

**Comment by necauqua** [comment]
> but we're splitting hairs here in a sense

~I am only pointing that out because your argument is that "we cannot switch to a HEAD@git, it doesn't really make sense" and it doesnt, but if we instead "create a new working copy commit as a child of commit referenced by HEAD@git" then it does 🤷~

~The original confusion was that commands don't work on what looks like a thing that they should work on - and imo there's nothing preventing them from actually working on them, erasing said confusion.~
realised I've read "I'm opposed to" where you wrote "I'm not opposed to", whoops

> extent some merit to being distinct

Yeah I don't argue with this PR, I was just emphasising that the real solution is (imo) to do the revset thing - only because you've set the PR to close the issue when merged :)

**Review by yuja — APPROVED** [review]
> Even if we do allow HEAD@git for revset syntax (which I'm not opposed to!) I also think there is to some extent some merit to being distinct between @git remotes and otherwise typical named references

+1

**Comment by thoughtpolice** [comment]
> Yeah I don't argue with this PR, I was just emphasising that the real solution is (imo) to do the revset thing - only because you've set the PR to close the issue when merged :)

Oh, that's a good point. I can fix it to not use the `Fixes` syntax as well before I push.

**Comment by ilyagr** [comment]
Is there any particular reason you chose "bright green" over just "green"?

**Pull request merged**
