### PR TITLE
Add sapling graph formatters as an option

### PR DESCRIPTION
**Pull request by MForster**
# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have added tests to cover my changes

### CODE REVIEW

**Comment by MForster** [comment]
> From testing, I think only `clap` needs to be upgraded in order to avoid this conflict. In any case, since upgrading `clap` changes the output, the requirement for `clap` should be explicitly set to `4.1.1` in `Cargo.toml`.

There were more issues from this update. I've reverted and only updated the bare minimum.

**Comment by martinvonz** [comment]
> I don't think I can avoid the `cargo-deny` issue with a forbidden dependency on `abomonation` without changes to sapling.

@quark-zju, @markbt: Is it easy to get rid of that use of `abomonation`? @quark-zju mentioned that you may also be able to decouple the graph-drawing part from the DAG part.

**Comment by martinvonz** [comment]
In the meantime, should we figure out how to tell cargo-deny to allow `abomonation`? Otherwise I can turn off `cargo-deny` as a required check, so it doesn't prevent this from merging the PR.

**Comment by MForster** [comment]
I disabled the `cargo deny` check and filed issue https://github.com/martinvonz/jj/issues/1056 to reenable it.

**Review by martinvonz — APPROVED** [review]
Thank you! I'm looking forward to trying this.

**Comment by markbt** [comment]
> Is it easy to get rid of that use of `abomonation`?

It's not easy, but the use of `abomonation` has coincidentally just cropped up on my radar, and I might see if it's possible to eliminate it, or at least make it optional.  Not sure if I'll be able to, or the timeline, but I'm looking into it.

**Pull request merged**
