### PR TITLE
cleanup: fix warnings from nightly clippy

### PR DESCRIPTION
**Pull request by martinvonz**
# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (src/config-schema.json)
- [ ] I have added tests to cover my changes

### CODE REVIEW

**Review by ilyagr — APPROVED** [review]

**Comment by ilyagr** [comment]
For `allow(format_collect)`, you can use the trick from https://github.com/martinvonz/jj/commit/738f99ddf117fb5c17fcdf75bc4472d6240c87c6.

**Comment by martinvonz** [comment]
> For `allow(format_collect)`, you can use the trick from [738f99d](https://github.com/martinvonz/jj/commit/738f99ddf117fb5c17fcdf75bc4472d6240c87c6).

Fixed, thanks.

**Comment by ilyagr** [comment]
I'm impressed the check about too many `#`s with raw strings now seems to understand it shouldn't touch `insta` snapshots.

**Comment by martinvonz** [comment]
> I'm impressed the check about too many `#`s with raw strings now seems to understand it shouldn't touch `insta` snapshots.

Maybe it leaves instances inside macros alone? I don't know if macros can see the number of `#`s so they could potentially behave differently depending on that.

**Comment by ilyagr** [comment]
I'm actually guessing that a recent version of `insta` fixed it by putting the `#[allow]` into the macro.

**Pull request merged**
