### PR TITLE
commands: destructure `SplitArgs` exhaustively

### PR DESCRIPTION
**Pull request by arxanas**
# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (cli/src/config-schema.json)
- [ ] I have added tests to cover my changes

### CODE REVIEW

**Review by martinvonz — COMMENTED** [review]
> To warn us to update use-sites when adding new flags.

Won't we get warned that we have an unused field anyway?

**Comment by arxanas** [comment]
@martinvonz That's true, but I generally find destructuring to be a better default for exhaustiveness-checking. If you ever use the same type in more than one function, you usually want to get exhaustiveness-checking in *all* the functions, not just one. It's also plausible that we would make the `struct` `pub` at some point in order to split subcommands into different crates, after which we would no longer get exhaustiveness-checking. git-branchless does this: https://github.com/arxanas/git-branchless/blob/d898f86a38ddaeeff8c4434b18fa29adb1cac8a8/git-branchless-test/src/lib.rs#L108

**Comment by arxanas** [comment]
We can drop this commit if you prefer not to make this change.

**Comment by arxanas** [comment]
I remember now the issue that made me do this: usually, I just add the new field to the struct and jump to the next error location (where a field has not been destructured), add the implementing code, and then repeat until I'm done, which I find to be a very productive workflow. The dead code warning only tells you that a field hasn't been used, not where it *ought* to be used, so you still have to spend time jumping around the code to find the right place to change.

**Pull request closed without merging**
