### PR TITLE
build: update rerun-if conditions to watch .git/HEAD in colocated repo

### PR DESCRIPTION
**Pull request by yuja**
# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (src/config-schema.json)
- [ ] I have added tests to cover my changes

### CODE REVIEW

**Review by thoughtpolice — APPROVED** [review]

**Comment by ilyagr** [comment]
A minor problem that also existed before this PR is that jj's version doesn't indicate whether the working dir is dirty or not. I think that's fixable with this approach; it doesn't have to go into this PR. Somebody (me, for example) just has to look up the git command to check for dirty dir.

**Comment by yuja** [comment]
> A minor problem that also existed before this PR is that jj's version doesn't indicate whether the working dir is dirty or not.

Including dirty flag would mean test-only change requires "rerun" + link everything. (dirty only for `{cli|lib}/src/` might work, though.)

If `$JJ_VERSION` is provided to `cargo` as an environment, cargo won't rebuild so long as `$JJ_VERSION` is stable. (so once the working dir gets dirty, it wouldn't require rebuild more than once.) I have no idea if we can configure `build.rs` that way.

**Comment by martinvonz** [comment]
Since `.git/HEAD` is (or can be?) a so-called "symbolic ref", which means it can point to a ref instead of directly at a commit, I think this change means that the version will not change when using git as long as you stay on a branch. So with this change, if the user does `git checkout -b my-branch X; cargo build; git reset --hard Y; cargo build`, I think the version number will now refer to X. I'm not sure if that will be a problem in practice. Maybe we should roll back that part of this PR?

**Comment by yuja** [comment]
> if the user does `git checkout -b my-branch X; cargo build; git reset --hard Y; cargo build`, I think the version number will now refer to X.

Yes, I assume that users would use `jj` (or detached HEAD) than `git`. BTW, in that workflow, `op_heads/heads/*` wouldn't be modified, so the version hash would be stale anyway.

**Pull request merged**
