### PR TITLE
merge_tools: pass `Matcher` in for interactive use

### PR DESCRIPTION
**Pull request by arxanas**
# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (cli/src/config-schema.json)
- [ ] I have added tests to cover my changes

### CODE REVIEW

**Comment by ilyagr** [comment]
Re commit message: `jj split` is already interactive. I think you might mean `jj commit --interactive PATHs` and `jj split --interactive PATHs`, which don't yet exist.

**Review by martinvonz — APPROVED** [review]
Sorry to keep this waiting, I don't know why I had not approved this earlier

**Comment by arxanas** [comment]
@ilyagr do you have a suggestion for an alternate commit message?

**Comment by ilyagr** [comment]
@arxanas My first thought is to replace `jj split` with `jj split <paths>` three times (twice in the commit description and once in the changelog).

If you don't like that and nothing else comes to mind, feel free to leave as is.

**Comment by arxanas** [comment]
@ilyagr ah, I think you meant to comment on https://github.com/martinvonz/jj/pull/2130 (which I mistakenly merged)? I'll see about updating that one.

**Comment by arxanas** [comment]
@ilyagr Okay, so looking back at it, the reason I added `--interactive` to `jj split` really *is* for the no-paths case. That is, I've been running `jj split -i` with no paths and wanting it to mean the same as `jj split`. But it has the actually-useful effect of restricting the set of paths to split, which is what most people would probably use it for, so I've updated the documentation/commit message to make that clearer.

**Pull request merged**
