### PR TITLE
revset: remove filter_by_diff(), have caller intersect expression

### PR DESCRIPTION
**Pull request by martinvonz**
# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (src/config-schema.json)
- [ ] I have added tests to cover my changes

### CODE REVIEW

**Review by ilyagr — APPROVED** [review]
Looks nice to me. I'm mainly relying on the tests passing to approve.

**Comment by martinvonz** [comment]
Thanks. I'll wait a bit so Yuya also gets a chance to review it since he wrote some of this code.

**Review by yuja — APPROVED** [review]
LGTM. Parsing/building matcher should be cheap.

**Comment by martinvonz** [comment]
> LGTM. Parsing/building matcher should be cheap.

Speaking of that, I think we shouldn't do this TODO: https://github.com/martinvonz/jj/blob/26597ba61a7e1946ac2b512d407d5c302c323585/lib/src/revset.rs#L340

By having more structured information in the `RevsetExpression`, we make it easier to e.g. evaluate that part on a server.

**Comment by yuja** [comment]
> Speaking of that, I think we shouldn't do this TODO:
> 
> https://github.com/martinvonz/jj/blob/26597ba61a7e1946ac2b512d407d5c302c323585/lib/src/revset.rs#L340
> 
> By having more structured information in the `RevsetExpression`, we make it easier to e.g. evaluate that part on a server.

In that TODO comment, I was thinking of `enum MatcherExpression { Prefix(Vec<RepoPath>), ... }`, not `Box<dyn Matcher>`.

**Comment by martinvonz** [comment]
> > Speaking of that, I think we shouldn't do this TODO:
> > https://github.com/martinvonz/jj/blob/26597ba61a7e1946ac2b512d407d5c302c323585/lib/src/revset.rs#L340
> > 
> > By having more structured information in the `RevsetExpression`, we make it easier to e.g. evaluate that part on a server.
> 
> In that TODO comment, I was thinking of `enum MatcherExpression { Prefix(Vec<RepoPath>), ... }`, not `Box<dyn Matcher>`.

Ah, I see. That sounds good. (I actually thought I had written that TODO.)

**Pull request merged**
