### PR TITLE
merge_tools: use `right_file_mode` in `make_diff_files`

### PR DESCRIPTION
**Pull request by crackcomm**
See the issue #2548 for more context.

It fixes the initially posted issue but it could remain open until [other](https://github.com/martinvonz/jj/issues/2548#issuecomment-1801130741) [related](https://github.com/martinvonz/jj/issues/2548#issuecomment-1806868455) issues are addressed by fixing the integration with `scm-record`, at least until another issue is opened to replace it.

# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (cli/src/config-schema.json)
- [ ] I have added tests to cover my changes

### CODE REVIEW

**Review by martinvonz — COMMENTED** [review]
LGTM. @arxanas, does this seem like a strict improvement to you or do you see any issues with it?

**Review by arxanas — APPROVED** [review]
This seems right to me.

**Comment by arxanas** [comment]
@crackcomm You'll need to update the snapshot tests either by copy-and-paste or by downloading the helper tool https://insta.rs/

**Comment by crackcomm** [comment]
> @crackcomm You'll need to update the snapshot tests either by copy-and-paste or by downloading the helper tool https://insta.rs/

yup, I was just waiting for your review.

**Comment by arxanas** [comment]
@crackcomm thank you for the fix!

**Pull request merged**
