### PR TITLE
Fix typo in docs

### PR DESCRIPTION
**Pull request by TheodoreEhrenborg**
# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (cli/src/config-schema.json)
- [ ] I have added tests to cover my changes

### CODE REVIEW

**Comment by PhilipMetzger** [comment]
Thanks for your contribution, but this is not a typo, as it recently was renamed. See 895d53f3958834e73c2d526c232ee3076cbe4842 for the details.

**Comment by TheodoreEhrenborg** [comment]
Aha, thanks for explaining

In that case, I've just changed `file` to `files` in the rest of that section, to match the rename

**Comment by PhilipMetzger** [comment]
If you can rewrite the commit description with `docs: fix typo` , I'll land it for you. See https://github.com/martinvonz/jj/blob/main/docs/contributing.md#code-reviews where I mean this part:

> The commit message should describe the changes in the commit; the PR description can even be empty, but feel free to include a personal message. We write commit messages in an affected component style and don't use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/). This means if you modified a command in the CLI, use its name as the topic, e.g `next/prev: <your-modification>` or `conflicts: <your-modification>`.

**Comment by martinvonz** [comment]
> If you can rewrite the commit description with `docs: fix typo`

I almost asked to update the description to be clearer but I didn't care enough. Since you're asking for an update anyway, I might as well. Can you make it `docs: update stale references to singular file() revset` or something like that? Thanks.

**Review by PhilipMetzger — APPROVED** [review]
Thanks again.

**Pull request merged**
