### PR TITLE
test_bad_locking: make `merge_directories()` expect non-existent target

### PR DESCRIPTION
**Pull request by martinvonz**
@colemickens, let me know if this makes any difference to #2103.

# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (cli/src/config-schema.json)
- [ ] I have added tests to cover my changes

### CODE REVIEW

**Comment by colemickens** [comment]
Might be hard to say, I just re-added `jj` to my config and it seemed to just build.

**Comment by martinvonz** [comment]
> Might be hard to say, I just re-added `jj` to my config and it seemed to just build. That is, the latest version from this repo, not this PR.

Weird that it's different now. I wish we knew why, but at least it's working for you (for now anyway), and I think this PR does fix some issues.

**Comment by colemickens** [comment]
Depending on how curious you are, I can rebuild with `--rebuild` in a loop and see if it fails.

Alternatively, now that I've re-enabled it, I'll end up rebuilding this somewhat often and will let you know if I see failures again (before or after you merge this).

**Comment by colemickens** [comment]
Well, okay, with tip of tree, this early afternoon:
* x86_64-linux (on a quad-core, ht system): **build failed on these tests**
* aarch64-linux (on a huge Ampere system): passed

When I switched my `jj` input to this PR's branch, it built on both systems first try.

Sample size of 1 each, basically, but it's what I can offer for now.

**Review by yuja — APPROVED** [review]

**Pull request merged**
