### PR TITLE
docs CLI Reference: upgrade `clap-markdown` to 0.1.4 (fixes important bugs)

### PR DESCRIPTION
**Pull request by ilyagr**
# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (cli/src/config-schema.json)
- [ ] I have added tests to cover my changes

### CODE REVIEW

**Review by thoughtpolice — APPROVED** [review]
Nice, the reference looks much better!

**Comment by ilyagr** [comment]
There are a few new imperfections, I might fix them in a separate PR:

image

**Comment by ilyagr** [comment]
I will wait for a few hours before merging, in case anyone has comments (or wants me to wait longer).

**Comment by ilyagr** [comment]
I added a minor fixup (comment deletion) as a separate commit.

**Pull request merged**
