### PR TITLE
jj run: describe it as a stub in the help text

### PR DESCRIPTION
**Pull request by ilyagr**
# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (cli/src/config-schema.json)
- [ ] I have added tests to cover my changes

### CODE REVIEW

**Review by thoughtpolice — APPROVED** [review]

**Comment by PhilipMetzger** [comment]
I dont think this makes a difference, since its hidden anyway.

**Comment by mhammond** [comment]
FWIW, I recently struck this. A colleague wished `jj run` wasn't a stub so they could use it. I thought that it was enabled by default in 0.19, so run `jj help run` and saw no evidence it was a stub, so started a conversation about "maybe you need to upgrade" etc. Joke was on me :)

**Comment by ilyagr** [comment]
Yeah, I wasn't sure this was necessary either, but I followed the logic of "well, it confused me, and I can fix it".

**Comment by PhilipMetzger** [comment]
If you want `jj run` you should just follow #4021, so it finally gets a implementation. My in-tree implementation is struggling no disagreement there though.

**Comment by PhilipMetzger** [comment]
I would've accepted it anyway since @mhammond opinion is valid and since we've seen people run into it already but since it was past midnight for me I was not the reviewer.

**Pull request merged**
