### PR TITLE
Allow \0 escape for nulls

### PR DESCRIPTION
**Pull request by Dr-Emann**
This allows safely getting e.g. multiple descriptions, and knowing where the boundaries are

# Checklist

If applicable:
- [x] I have updated `CHANGELOG.md`
- [x] I have added tests to cover my changes
- N/A I have updated the documentation (README.md, docs/, demos/)
- N/A I have updated the config schema (cli/src/config-schema.json)

### CODE REVIEW

**Review by martinvonz — APPROVED** [review]
Thanks!

**Review by ilyagr — APPROVED** [review]
Interestingly (er... to me), the following doesn't seem to print any null characters:

    $ jj log -T $(printf '"a\0b"')

In `fish`, I also get:

```
    fish> jj log -T '"'a \0 b'"'
Error: Failed to parse template:  --> 1:3
  |
1 | "a
  |   ^---
  |
  = expected escape or raw_literal
```

Meanwhile, this does work. 

    $ jj log -T $(printf '"a\1b"')

So, it makes sense to add "\0" and not "\1".

**Review by yuja — APPROVED** [review]
If you like, you can update `test_string_literal()` in template_parser.rs. I think it's also good to have e2e test since null character is a bit special, so I wouldn't remove all of the CLI tests.

**Comment by Dr-Emann** [comment]
> Interestingly (er... to me), the following doesn't seem to print any null characters:
> 
> ```
> $ jj log -T $(printf '"a\0b"')
> ```

I believe it's actually _impossible_ to pass a real null byte as a parameter: parameters are null-terminated strings all the way down to the exec syscalls. Presumably, bash is stripping out the null, and fish is probably actually setting the parameter exactly as the string you specified, and so ends up terminating the parameter early at the exec call.

**Comment by Dr-Emann** [comment]
Added to `test_string_literal` as well

**Pull request merged**
