### PR TITLE
Shiny default graph symbols, take 2

### PR DESCRIPTION
**Pull request by algmyr**
I split this into a few commit to keep @thoughtpolice's initial commit intact, put my fixes on top, and shove all the tests into a separate commit to make reviewing hopefully less terrible.

Screenshot showing the new proposed style, both non-ascii and ascii style
image

# Checklist

If applicable:
- [x] I have updated `CHANGELOG.md`
- [x] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (cli/src/config-schema.json)
- [x] I have added tests to cover my changes

### CODE REVIEW

**Comment by martinvonz** [comment]
One option is to start with aliases as Yuya suggested in https://github.com/martinvonz/jj/pull/3381#issuecomment-2052889923. We could leave updating the default for later, after we've heard feedback from some users. That way we could potentially avoid updating all the tests multiple times. I don't feel strongly.

**Comment by joyously** [comment]
I haven't really been following the evolution of which symbols are used in the graph, but it looks like it changed the normal node from a solid circle to an empty circle. I have two concerns with that. One, which I mentioned on an issue some time back is that the empty circle and the ASCII equivalent looks like a valid change ID.  Secondly, it looks so similar to `@`. (as does the circle with inner dot)
Why was the default changed?

**Comment by joyously** [comment]
> the previous thing wasn't a solid circle, it was a fisheye, a circle with a dot inside

Ha ha! It looked solid to me when viewing the file changes on GitHub.
I complained to Ilya recently that the circle with a dot looked too much like `@` also...
It looks different in your message where you type it than it does in the image.

> I would have assumed that with the neutral color of the graph node compared to the change ids that wouldn't be an issue. 

That's fine for looking at the CLI output with good vision. I was looking at code in a diff on GitHub, and there are lots of people that don't have good vision (I guess me, since I couldn't see the dot in the circle) and could be looking at a cut/paste instead of a colored output. My comment about the `o` that was in use when I first found this project stemmed from the density of the `log` output. Perhaps it has improved somewhat, or once you know what you are looking at, it's easier to read (but at first it's a mess).

**Comment by algmyr** [comment]
Right, looking at the code gets messy, especially since I wouldn't be surprised if the font rendering looks quite different from what you might expect in a terminal. Let me pop a proper screenshot that has all the symbols up top.

**Comment by algmyr** [comment]
> One option is to start with aliases as Yuya suggested in [#3381 (comment)](https://github.com/martinvonz/jj/pull/3381#issuecomment-2052889923). We could leave updating the default for later, after we've heard feedback from some users. That way we could potentially avoid updating all the tests multiple times. I don't feel strongly.

To follow up on this, I prepared this in #3501.

I'll close this for the time being since we seem to be going down the route of not shipping a new default config yet, but rather having something opt in for now.

**Pull request closed without merging**
