### PR TITLE
cli: replace `o` as graph node by `●`

### PR DESCRIPTION
**Pull request by martinvonz**
I'll update the screenshots if people like this change.

# Checklist

If applicable:
- [x] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (src/config-schema.json)
- [x] I have added tests to cover my changes

### CODE REVIEW

**Comment by yuja** [comment]
The character `●` (U+25CF) has a historical problem, which may occupy 2 ascii-character width depending on environment.
https://www.unicode.org/reports/tr11-2/

It's okay for unicode graph (since some of the graph characters have this problem anyway), but better to not use non-ascii character for ascii graphs.

**Comment by martinvonz** [comment]
> The character `●` (U+25CF) has a historical problem, which may occupy 2 ascii-character width depending on environment. https://www.unicode.org/reports/tr11-2/
> 
> It's okay for unicode graph (since some of the graph characters have this problem anyway), but better to not use non-ascii character for ascii graphs.

Makes sense. I've updated it to still use `o` for the ascii graph styles.

**Comment by martinvonz** [comment]
I didn't hear any objections, so I updated the screenshots.

**Review by Ralith — APPROVED** [review]

**Comment by necauqua** [comment]
Too late to the party, but I've just noticed this after updating `jj` - and this slightly clashes mentally for people (like me) who used git-branchless:
The ● (or ◆) symbol there means "current head" and ◯/◇ is used for other commits - in jj all the commits are ● and the wc is @ which is kind of looks like ◯, so it's backwards and the intuition is super-wrong now and confusing for a 0.1s on every `jj log` :)

In the end those symbols should probably be customizable by a config

**Comment by martinvonz** [comment]
> In the end those symbols should probably be customizable by a config

Yes, that makes sense.

> Also another (very slight) collision is the unicode symbol being very geometric and unicode-y and plain boring @ contrasts with it (slightly) unpleasantly as well 🤷, maybe thats just me though

It's not just you - I feel the same way. I really don't want to change the `@` symbol to something else, because I think it's useful to help reinforce the association between `@` and the working-copy commit we have in revsets. So I guess the other choice would be to use a plain ASCII symbol like `*` (I think that's what Git does). The mismatch doesn't bother me enough to do that, however :)

**Pull request merged**
