### PR TITLE
nix: use mold linker on Linux

### PR DESCRIPTION
**Pull request by thoughtpolice**
Summary: Pure QOL improvement, not that this was too awful as it stood. But this ultimately makes all builds faster, effectively for free; on my Linux machine, debug link time for jj-cli goes from 3s to 1s.

This was originally submitted as part of https://github.com/martinvonz/jj/pull/1864, and backed out as part of https://github.com/martinvonz/jj/pull/1982, because the default `mold` package did not have the proper "wrapper script" that allowed it to find the right external libraries. Using the `mold-wrapped` package however fixes this.

On top of that, let's go ahead and make `mold` the default linker in the Nix package/flake as well; this should improve the `nix build` speed since a lot of tests need to be linked.

On my machine, the following command, which causes a relink of all tests and the `jj` binary, goes from 1m27s to 45s, nearly halving the time &mdash; which is fairly significant when iterating in the test suite.

```
austin@GANON:~/src/jj$ echo >> lib/src/lib.rs 
austin@GANON:~/src/jj$ time cargo test --workspace --no-run
```

### CODE REVIEW

**Comment by ilyagr** [comment]
I could stamp this if you like, but I'd rather somebody who understands Nix better looked at it.

Non-blocking: I think the main benefit is when testing. It might also make sense to make `nix build` use `nextest` if it isn't already.

**Comment by thoughtpolice** [comment]
Nix is already using nextest, so I think we're in the clear, there. An approval would be nice though; perhaps @necauqua could also provide one, since it would speed up his work too hopefully.

**Review by ilyagr — APPROVED** [review]
OK, I'll stamp this based mainly on the CI passing and the fact that mold seems helpful outside nix. I'll leave it up to you whether to wait for other reviews.

**Comment by thoughtpolice** [comment]
Ahhhhhh, I forgot I enabled auto merge, so we'll just do it live. :) I feel pretty safe about it this time, though.

**Comment by ilyagr** [comment]
Maybe we should suggest a Github feature that pops a warning when you resolve the last thread when auto-merge is on.

I have almost learned to never turn auto-merge on before a PR is approved. Still, I do it sometimes, and I regret it 50% of those times. Makes me chuckle; I guess it feels like a lesson about hubris and human folly.

**Pull request merged**
