### PR TITLE
templater: add `object.field` syntax, migrate some nullary methods

### PR DESCRIPTION
**Pull request by yuja**
# Checklist

If applicable:
- [x] I have updated `CHANGELOG.md`
- [x] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (src/config-schema.json)
- [x] I have added tests to cover my changes

### CODE REVIEW

**Review by martinvonz — COMMENTED** [review]
> We can of course remove object.field syntax at all and map all commit keywords to nullary methods.

Or we can follow your rule and make only some of them use function syntax: `divergent()`, `conflict()`, `empty()`.

Another, and orthogonal, option is to say that there keywords are not different from functions, by instead having a top-level variable called e.g. `commit`, so the current `change_id` would become `commit.change_id` and `divergent` would be `commit.divergent()`. The top-level scope would then be similar to a lambda that introduced a `commit` variable (EDIT: or call it `self`). It would make the difference between methods and free functions clear in the syntax. That seems consistent, but I don't know if it's worth the extra verbosity in templates. What do you think?

**Comment by yuja** [comment]
> > We can of course remove object.field syntax at all and map all commit keywords to nullary methods.
> 
> Or we can follow your rule and make only some of them use function syntax: `divergent()`, `conflict()`, `empty()`.

True. We can also turn most nullary methods (`.first_line`, `.lines`, `.duration`, `.ago`) into fields. I wouldn't change `.upper()` and `.lower()` though.

> Another, and orthogonal, option is to say that there keywords are not different from functions, by instead having a top-level variable called e.g. `commit`, so the current `change_id` would become `commit.change_id` and `divergent` would be `commit.divergent()`. The top-level scope would then be similar to a lambda that introduced a `commit` variable (EDIT: or call it `self`). It would make the difference between methods and free functions clear in the syntax. That seems consistent, but I don't know if it's worth the extra verbosity in templates.

Yeah. For stock templates, the extra verbosity doesn't matter, but I wouldn't want to type `commit.` for every keyword in `-T`/`--template`.

Regarding `self.` vs `commit.`, maybe we can use lambda syntax to explicitly capture the context parameter.

**Comment by martinvonz** [comment]
> We can also turn most nullary methods (`.first_line`, `.lines`, `.duration`, `.ago`) into fields. I wouldn't change `.upper()` and `.lower()` though.

I wouldn't probably not turn any of those methods into fields. We also have to keep in mind the risk of any future parameters to any of these methods. For example, `.first_line` and `.lines` could conceivably gain an argument to decide which characters to consider when splitting (CR/LF/CRLF).

> Regarding `self.` vs `commit.`, maybe we can use lambda syntax to explicitly capture the context parameter.

That wouldn't come into play if we don't introduce a variable for the context parameter at all, right? Or do you mean that we could do that even if we don't have a `self`/`commit` variable?

I should also say that I think the PR looks good, but it's probably good to give others a chance to comment since it has non-trivial impact on the UX.

**Review by martinvonz — APPROVED** [review]

**Comment by yuja** [comment]
> > We can also turn most nullary methods (`.first_line`, `.lines`, `.duration`, `.ago`) into fields. I wouldn't change `.upper()` and `.lower()` though.
> 
> I wouldn't probably not turn any of those methods into fields. We also have to keep in mind the risk of any future parameters to any of these methods. For example, `.first_line` and `.lines` could conceivably gain an argument to decide which characters to consider when splitting (CR/LF/CRLF).

Good point. These functions can also take `keep_ends=true`.

> > Regarding `self.` vs `commit.`, maybe we can use lambda syntax to explicitly capture the context parameter.
> 
> That wouldn't come into play if we don't introduce a variable for the context parameter at all, right? Or do you mean that we could do that even if we don't have a `self`/`commit` variable?

If the top-level expression is lambda, pass context to it. So `summary = |c| c.description.first_line()` can be used in both `-Tsummary` and `-Tparents.map(summary)` positions.

> it's probably good to give others a chance to comment since it has non-trivial impact on the UX.

+1

**Comment by ilyagr** [comment]
I personally like the consistency of having fewer concepts (fields vs methods vs functions).

One possible idea, if we don't like parentheses, is to simply declare that, for nullary methods, `a.b` and `a.b()`  are equivalent.

I can immediately think of two reasons for a programming language to distinguish between a field and a nullary method, but neither of them seems to apply here:

- A field is cheap to compute. (But, ideally, users of the templating language shouldn't have to worry about performance).
- A field can be set. (But that doesn't apply to a functional templating language)

Are there more reasons I haven't thought of? Or are you thinking of adding ways to change a single field (e.g. email) within a commit inside the templating language?

As a slightly separate topic, I'd also love for `a.b(c, d)` and `b(a, c, d)` to be equivalent, or to find some other way to not require users to remember what's a function and what's a method. The one problem with that is that sometimes `one_type.b()` and `another_type.b()` have different implementations, but they could dispatch on type.

**Comment by yuja** [comment]
> I personally like the consistency of having fewer concepts (fields vs methods vs functions).

+1

> One possible idea, if we don't like parentheses, is to simply declare that, for nullary methods, `a.b` and `a.b()` are equivalent.

I understand your points, but I prefer not doing that because function and symbol are different in revset language. We won't need such distinction in template language (because keywords can't be overridden by repository content), but I want to keep these two languages structurally the same.

**Comment by ilyagr** [comment]
> because function and symbol are different in revset language. We won't need such distinction in template language (because keywords can't be overridden by repository content),

I didn't quite understand the explanation, perhaps because I haven't spent much time thinking about the grammar. Are you implying that asking the parser to treat fields as functions would make the part of the grammar that's shared between the two languages too confusing? That's my guess. 

If fields and methods must be separate, we could still have a convention (perhaps enforced to some degree) that whenever `a.b()` exists, `a.b` must exist and mean the same thing (and vice-versa).

If that seems too awkward, my current preference would be to keep having parentheses either everywhere or nowhere so that only one of the concepts of fields and nullary methods exists. This preference is driven mainly by the desire to avoid having to decide what should be a method and what should be a function. I worry that, one day, we'll inevitably be annoyed that we made the wrong choice for something and by then it'll be too late to change. OTOH, I think that'd be a mild annoyance rather than a catastrophe, so this is only a preference.

**Comment by yuja** [comment]
If `a.b()` is equivalent to `a.b`, I would naturally think `a()` is equivalent to `a`. That's acceptable for template, but `all()` and `all` are different in revset (the latter may be a tag "all"). I don't wanna make revset and template different languages at that level.

> If that seems too awkward, my current preference would be to keep having parentheses either everywhere or nowhere so that only one of the concepts of fields and nullary methods exists.

You mean `commit.commit_id()` (for a property of the `Commit` type)? Yes, that's one way to avoid thinking of `x.f()` vs `x.f`.

**Comment by ilyagr** [comment]
> If a.b() is equivalent to a.b, I would naturally think a() is equivalent to a. 

I see your point. I might still be OK with doing the former and not the latter, but this perspective does make it look problematic enough that maybe it's not worth it.

> You mean commit.commit_id() (for a property of the Commit type)?

Yes, exactly.

**Comment by PhilipMetzger** [comment]
> I personally like the consistency of having fewer concepts (fields vs methods vs functions).

I agree and I like having fields in the template syntax, as it just feels very consistent. As long as we have some guidance to distinguish when a new revset is an object, function or field, I'm fine with the change.

**Comment by yuja** [comment]
(closed by mistake while debugging github issue. will reopen later)

**Comment by martinvonz** [comment]
We talked about this in a meeting at Google today. The consensus seemed to be that the field syntax makes it non-obvious when to use parentheses and when not to. Also, it's obviously easier to add field syntax later than it is to remove it later if we felt that it was a mistake. We already quite frequently make compatibility-breaking changes like that, so that's more a concern that we might realize that it's a mistake after we've reached 1.0.

Some other thoughts that came up (not saying we should do any of these):

* If we wanted a top-level `self` variable and methods on that instead of the multiple variables (keywords) we currently have, we could make keywords (or some of them) aliases. For example, we could define `change_id` as an alias for `self.change_id()`.
* Should we have a syntax to clearly distinguish template aliases from builtins? That could be a leading `$` on the alias name. 
* How do we handle custom methods and types? It would be nice if custom methods could be added without feeling out of place. For example, Google and others might want to have a `.review_id()` or `.review_url()` method on a commit. I feel like that should be possible to do but I haven't thought much about it.

To be clear, the preference for method syntax over field syntax just seemed to be the consensus in that meeting; I don't think any of us felt very strongly about it. What do you think?

**Pull request closed without merging**
