### PR TITLE
github: don't override nixpkgs version (use the lock file's version) 

### PR DESCRIPTION
**Pull request by martinvonz**
# Checklist

- [x] I have made relevant updates to `CHANGELOG.md`

### CODE REVIEW

**Comment by arxanas** [comment]
Oh, hm, it looks like this duplicates changes from https://github.com/martinvonz/jj/pull/300, so maybe I wasn't supposed to merge that one 😬 . I'll leave this unmerged for you to manually merge to avoid maybe messing things up further.

**Comment by martinvonz** [comment]
> Oh, hm, it looks like this duplicates changes from #300, so maybe I wasn't supposed to merge that one 😬 .

Getting that merged first was the goal, so you did the right thing :)

> I'll leave this unmerged for you to manually merge to avoid maybe messing things up further.

I meant to leave auto-merge off on this one (not sure if I did or if you fixed that for me).

**Comment by martinvonz** [comment]
> Oh, was this supposed to be a stacked diff? I would have expected the `base` to have been set to the other PR in that case.

Yes, it was supposed to be. I spent a few seconds trying to set the base but I was lazy and gave up. I know I have figured out how to do it before.

**Comment by martinvonz** [comment]
> > Oh, was this supposed to be a stacked diff? I would have expected the `base` to have been set to the other PR in that case.
> 
> Yes, it was supposed to be. I spent a few seconds trying to set the base but I was lazy and gave up. I know I have figured out how to do it before.

Ah, it *was* that "Edit" button that I tried. I just didn't notice that the branch name became a drop-down box when I tried it earlier.

**Comment by arxanas** [comment]
By the way, I typically use `gh pr create --base XXX` on the command-line to create my PRs, rather than use the web UI; I think it's a bit easier to access those kinds of options.

**Pull request merged**
