### PR TITLE
Config changes

### PR DESCRIPTION
**Pull request by martinvonz**
This PR drops support for `~/.jjconfig`, add support for `$JJ_CONFIG` environment variable, and adds support for `$NO_COLOR`. Seems like your domain, @colemickens, if you have time.

### CODE REVIEW

**Comment by colemickens** [comment]
Just noting that the config loading env var overriding is not handled in the library but now in the binary, but I assume that was intentional and seems right to me.

**Comment by martinvonz** [comment]
> Just noting that the config loading env var overriding is not handled in the library but now in the binary, but I assume that was intentional and seems right to me.

You mean the `$JJ_CONFIG` env var? Yes, that was intentional (added in commit [aebb3fa](https://github.com/martinvonz/jj/pull/165/commits/aebb3fa7be28c0055829733b05b07df8cf50355d)).

Thanks for reviewing.

**Comment by colemickens** [comment]
And the other `JJ_*` vars. I was just highlighting that tools that use `jj` as a lib would (probably correctly) need to manually support them.

**Comment by martinvonz** [comment]
Ah, yes, good point. That was intentional, and I should have mentioned that in the commit message of [771a3a3](https://github.com/martinvonz/jj/pull/165/commits/771a3a3cab38b3f168a1233b5c77f70958ba58eb). The reasoning is similar, though, which is that the library crate should be usable by e.g. server processes. The library should probably not read anything (?) from the environment at all.

**Pull request merged**
