### PR TITLE
docs: fix contributing.md

### PR DESCRIPTION
**Pull request by thoughtpolice**
Summary: This was some fallout from merging #1851; I missed a few changes I needed to back out for an upcoming diff.

# Checklist

If applicable:
- [ ] I have updated `CHANGELOG.md`
- [ ] I have updated the documentation (README.md, docs/, demos/)
- [ ] I have updated the config schema (src/config-schema.json)
- [ ] I have added tests to cover my changes

### CODE REVIEW

**Comment by thoughtpolice** [comment]
Just hitting the big automerge button on this one.

**Review by ilyagr — COMMENTED** [review]
Around line 120, should we mention that the version is now 1.71?

Alternatively, I had a passage that referred the user to `Cargo.toml` for the actual value.

We can have one or both of these, but I think there should be some sort of pointer.

**Comment by thoughtpolice** [comment]
Yeah, those also got lost. I'll try to add a little more detail

**Review by ilyagr — APPROVED** [review]
Thanks!

**Pull request merged**
